import {
  AlertTriangle,
  Archive,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Car,
  ClipboardList,
  Code2,
  Contact,
  Database,
  FileText,
  FolderTree,
  Gauge,
  Home,
  KeyRound,
  LayoutDashboard,
  MessageSquare,
  MonitorCog,
  Package,
  ScrollText,
  Settings,
  Shield,
  Stamp,
  TableProperties,
  Truck,
  UserCog,
  Users,
  WalletCards,
  Workflow
} from 'lucide-vue-next'
import type { Component } from 'vue'

const icons: Record<string, Component> = {
  dashboard: LayoutDashboard,
  home: Home,
  user: Users,
  users: Users,
  role: Shield,
  menu: FolderTree,
  file: FileText,
  tenant: Building2,
  schedule: Calendar,
  meeting: Calendar,
  attendance: Calendar,
  asset: Package,
  vehicle: Car,
  workflow: Workflow,
  form: ClipboardList,
  alert: AlertTriangle,
  monitor: Gauge,
  expense: WalletCards,
  payment: WalletCards,
  purchase: Truck,
  announcement: Bell,
  notice: MessageSquare,
  log: ScrollText,
  dict: BookOpen,
  code: Code2,
  hr: UserCog,
  contract: FileText,
  seal: Stamp,
  license: KeyRound,
  visitor: Contact,
  supplier: Briefcase,
  consumable: Package,
  risk: AlertTriangle,
  template: TableProperties,
  archive: Archive,
  cache: Database,
  config: MonitorCog,
  setting: Settings,
  settings: Settings
}

export const getIcon = (name?: string): Component => {
  if (!name) return LayoutDashboard
  const key = name.toLowerCase().replace(/^icon-/, '')
  return icons[key] ?? LayoutDashboard
}
