export interface CloudFlowRouteMeta {
  path: string
  title: string
  source: string
  group: string
  mobile?: boolean
  public?: boolean
  redirect?: string
  componentKey?: string
  permissions?: string[]
  roles?: string[]
}

export const desktopRouteCatalog: CloudFlowRouteMeta[] = [
  { path: '/', title: '仪表盘', source: 'cloudflow-frontend/src/pages/Dashboard.tsx', group: '工作台', componentKey: 'dashboard', permissions: ['oa:workplace:view'] },
  { path: '/dashboard', title: '仪表盘', source: 'cloudflow-frontend/src/pages/Dashboard.tsx', group: '工作台', componentKey: 'dashboard', permissions: ['oa:workplace:view'] },
  { path: '/workplace', title: '发起流程', source: 'cloudflow-frontend/src/pages/Workplace.tsx', group: '流程中心', componentKey: 'processCenter', permissions: ['oa:workplace:view'] },
  { path: '/profile', title: '个人资料', source: 'cloudflow-frontend/src/pages/ProfilePage.tsx', group: '工作台', componentKey: 'profile', permissions: ['system:user:profile:view'] },
  { path: '/tasks', title: '审批待办', source: 'cloudflow-frontend/src/pages/TaskListPage.tsx', group: '流程中心', componentKey: 'processCenter', permissions: ['workflow:task:todo'] },
  { path: '/announcement', title: '公告消息', source: 'cloudflow-frontend/src/pages/AnnouncementPage.tsx', group: '工作台', componentKey: 'officeAnnouncement', permissions: ['oa:announcement:list'] },
  { path: '/office/announcement', title: '办公公告', source: 'cloudflow-frontend/src/pages/AnnouncementPage.tsx', group: 'OA 办公', componentKey: 'officeAnnouncement', permissions: ['oa:announcement:list'] },
  { path: '/schedule', title: '日程管理', source: 'cloudflow-frontend/src/pages/SchedulePage.tsx', group: 'OA 办公', componentKey: 'schedule', permissions: ['oa:schedule:list'] },
  { path: '/meeting-room', title: '会议室', source: 'cloudflow-frontend/src/pages/MeetingRoomPage.tsx', group: 'OA 办公', componentKey: 'adminLedger', permissions: ['oa:meeting-room:list'] },
  { path: '/my-apps', title: '我的申请', source: 'cloudflow-frontend/src/pages/TaskListPage.tsx', group: '流程中心', componentKey: 'processCenter', permissions: ['workflow:process:mine'] },
  { path: '/my-copies', title: '抄送我的', source: 'cloudflow-frontend/src/pages/CopyListPage.tsx', group: '流程中心', componentKey: 'processCenter', permissions: ['workflow:copy:list'] },
  { path: '/workflow', title: '发起流程', source: 'cloudflow-frontend/src/pages/WorkflowCreate.tsx', group: '工作流', componentKey: 'workflowCreate', permissions: ['workflow:process:start'] },
  { path: '/workflow/create', title: '发起流程', source: 'cloudflow-frontend/src/pages/WorkflowCreate.tsx', group: '工作流', componentKey: 'workflowCreate', permissions: ['workflow:process:start'] },
  { path: '/workflow/design', title: '流程设计', source: 'cloudflow-frontend/src/pages/WorkflowDesign.tsx', group: '工作流', componentKey: 'workflowDesign', permissions: ['workflow:definition:list'] },
  { path: '/workflow/monitor', title: '流程监控', source: 'cloudflow-frontend/src/pages/WorkflowMonitor.tsx', group: '工作流', componentKey: 'workflowAdmin', permissions: ['workflow:monitor:list'] },
  { path: '/workflow/deploy', title: '部署管理', source: 'cloudflow-frontend/src/pages/DeployManagement.tsx', group: '工作流', componentKey: 'workflowAdmin', permissions: ['workflow:deploy:list'] },
  { path: '/workflow/alerts', title: '流程预警', source: 'cloudflow-frontend/src/pages/AlertList.tsx', group: '工作流', componentKey: 'workflowAdmin', permissions: ['workflow:alert:list'] },
  { path: '/workflow/performance', title: '性能统计', source: 'cloudflow-frontend/src/pages/PerformanceStats.tsx', group: '工作流', componentKey: 'workflowAdmin', permissions: ['workflow:performance:view'] },
  { path: '/forms', title: '表单设计', source: 'cloudflow-frontend/src/pages/FormDesign.tsx', group: '工作流', componentKey: 'workflowAdmin', permissions: ['workflow:form:list'] },
  { path: '/users', title: '组织架构', source: 'cloudflow-frontend/src/pages/OrgStructurePage.tsx', group: '系统管理', componentKey: 'systemOrgStructure', permissions: ['system:dept:list'] },
  { path: '/code', title: '代码生成', source: 'cloudflow-frontend/src/pages/CodeGeneration.tsx', group: '系统管理', componentKey: 'systemCodeGeneration', permissions: ['system:code:list'] },
  { path: '/system/users', title: '用户管理', source: 'cloudflow-frontend/src/pages/system/UserList.tsx', group: '系统管理', componentKey: 'systemUser', permissions: ['system:user:list'] },
  { path: '/system/roles', title: '角色管理', source: 'cloudflow-frontend/src/pages/system/RoleList.tsx', group: '系统管理', componentKey: 'systemRole', permissions: ['system:role:list'] },
  { path: '/system/menus', title: '菜单管理', source: 'cloudflow-frontend/src/pages/system/MenuList.tsx', group: '系统管理', componentKey: 'systemMenu', permissions: ['system:menu:list'] },
  { path: '/system/files', title: '文件管理', source: 'cloudflow-frontend/src/pages/system/FileList.tsx', group: '系统管理', componentKey: 'systemFile', permissions: ['system:file:list'] },
  { path: '/system/tenant', title: '租户管理', source: 'cloudflow-frontend/src/pages/system/TenantList.tsx', group: '系统管理', componentKey: 'systemTenant', permissions: ['system:tenant:list'] },
  { path: '/hr/attendance/checkin', title: '考勤打卡', source: 'cloudflow-frontend/src/pages/admin/attendance/AttendanceCheckIn.tsx', group: 'HR 人事', componentKey: 'attendanceCheckIn' },
  { path: '/hr/attendance/rule', title: '考勤规则', source: 'cloudflow-frontend/src/pages/admin/attendance/AttendanceRule.tsx', group: 'HR 人事', componentKey: 'attendanceRule' },
  { path: '/hr/attendance/statistics', title: '考勤统计', source: 'cloudflow-frontend/src/pages/admin/attendance/AttendanceStatisticsPage.tsx', group: 'HR 人事', componentKey: 'hrAttendanceStatistics' },
  { path: '/admin/asset', title: '资产管理', source: 'cloudflow-frontend/src/pages/admin/asset/AssetList.tsx', group: '行政管理', componentKey: 'adminLedger', permissions: ['oa:asset:list'] },
  { path: '/admin/vehicle', title: '车辆管理', source: 'redirect:/admin/vehicle/list', group: '行政管理', componentKey: 'adminLedger', redirect: '/admin/vehicle/list' },
  { path: '/admin/vehicle/list', title: '车辆列表', source: 'cloudflow-frontend/src/pages/admin/vehicle/VehicleList.tsx', group: '行政管理', componentKey: 'adminLedger', permissions: ['oa:vehicle:list'] },
  { path: '/admin/vehicle/booking', title: '用车申请', source: 'cloudflow-frontend/src/pages/admin/vehicle/VehicleBooking.tsx', group: '行政管理', componentKey: 'adminLedger', permissions: ['oa:vehicle:booking'] },
  { path: '/admin/vehicle/usage', title: '车辆使用', source: 'cloudflow-frontend/src/pages/admin/vehicle/VehicleUsageList.tsx', group: '行政管理', componentKey: 'adminLedger', permissions: ['oa:vehicle:usage'] },
  { path: '/expense/claim', title: '费用报销', source: 'cloudflow-frontend/src/pages/ExpenseClaimPage.tsx', group: '财务管理', componentKey: 'adminLedger', permissions: ['oa:expense:list'] },
  { path: '/payment/request', title: '付款申请', source: 'cloudflow-frontend/src/pages/PaymentRequestPage.tsx', group: '财务管理', componentKey: 'adminLedger', permissions: ['oa:payment:list'] },
  { path: '/office/purchase-request', title: '采购申请', source: 'cloudflow-frontend/src/pages/PurchaseRequestPage.tsx', group: 'OA 办公', componentKey: 'adminLedger', permissions: ['oa:purchase:list'] },
  { path: '/office/seal-application', title: '用印申请', source: 'cloudflow-frontend/src/pages/SealApplicationPage.tsx', group: 'OA 办公', componentKey: 'adminLedger', permissions: ['oa:seal:list'] },
  { path: '/office/license-borrow', title: '证照借用', source: 'cloudflow-frontend/src/pages/LicenseBorrowPage.tsx', group: 'OA 办公', componentKey: 'adminLedger', permissions: ['oa:license:list'] },
  { path: '/office/contracts', title: '合同管理', source: 'cloudflow-frontend/src/pages/ContractPage.tsx', group: 'OA 办公', componentKey: 'adminLedger', permissions: ['oa:contract:list'] },
  { path: '/system/log', title: '操作日志', source: 'cloudflow-frontend/src/pages/system/OperationLogPage.tsx', group: '系统管理', componentKey: 'systemLog', permissions: ['system:log:list'] },
  { path: '/system/audit-log', title: '审计日志', source: 'cloudflow-frontend/src/pages/system/AuditLogPage.tsx', group: '系统管理', componentKey: 'systemAuditLog', permissions: ['system:audit:list'] },
  { path: '/system/login-log', title: '登录日志', source: 'cloudflow-frontend/src/pages/system/LoginLogPage.tsx', group: '系统管理', componentKey: 'systemLog', permissions: ['system:login-log:list'] },
  { path: '/system/online', title: '在线用户', source: 'cloudflow-frontend/src/pages/system/OnlineUserPage.tsx', group: '系统管理', componentKey: 'systemOnlineUser', permissions: ['system:online:list'] },
  { path: '/hr/attendance/supplement', title: '补卡申请', source: 'cloudflow-frontend/src/pages/AttendanceSupplementPage.tsx', group: 'HR 人事', componentKey: 'attendanceSupplement' },
  { path: '/hr/overtime/applications', title: '加班申请', source: 'cloudflow-frontend/src/pages/OvertimeApplicationPage.tsx', group: 'HR 人事', componentKey: 'hrApplication' },
  { path: '/hr/leave/application', title: '请假申请', source: 'cloudflow-frontend/src/pages/LeaveApplicationPage.tsx', group: 'HR 人事', componentKey: 'hrApplication' },
  { path: '/office/business-trip', title: '出差申请', source: 'cloudflow-frontend/src/pages/BusinessTripPage.tsx', group: 'OA 办公', componentKey: 'adminLedger', permissions: ['oa:trip:list'] },
  { path: '/office/contact', title: '通讯录', source: 'cloudflow-frontend/src/pages/ContactPage.tsx', group: 'OA 办公', componentKey: 'officeContact', permissions: ['oa:contact:list'] },
  { path: '/office/knowledge', title: '知识库', source: 'cloudflow-frontend/src/pages/KnowledgePage.tsx', group: 'OA 办公', componentKey: 'officeKnowledge', permissions: ['oa:knowledge:list'] },
  { path: '/admin/visitor', title: '访客管理', source: 'cloudflow-frontend/src/pages/VisitorPage.tsx', group: '行政管理', componentKey: 'adminLedger', permissions: ['oa:visitor:list'] },
  { path: '/admin/duty-schedule', title: '值班排班', source: 'cloudflow-frontend/src/pages/DutySchedulePage.tsx', group: '行政管理', componentKey: 'adminLedger', permissions: ['oa:duty:list'] },
  { path: '/admin/supplier', title: '供应商', source: 'cloudflow-frontend/src/pages/admin/supplier/SupplierPage.tsx', group: '行政管理', componentKey: 'adminLedger', permissions: ['oa:supplier:list'] },
  { path: '/admin/consumable', title: '耗材管理', source: 'cloudflow-frontend/src/pages/admin/consumable/ConsumablePage.tsx', group: '行政管理', componentKey: 'adminLedger', permissions: ['oa:consumable:list'] },
  { path: '/admin/seal', title: '印章管理', source: 'cloudflow-frontend/src/pages/admin/seal-license/SealListPage.tsx', group: '行政管理', componentKey: 'adminLedger', permissions: ['oa:seal:list'] },
  { path: '/admin/license', title: '证照管理', source: 'cloudflow-frontend/src/pages/admin/seal-license/LicenseListPage.tsx', group: '行政管理', componentKey: 'adminLedger', permissions: ['oa:license:list'] },
  { path: '/admin/borrow-management', title: '借用管理', source: 'cloudflow-frontend/src/pages/admin/seal-license/BorrowManagementPage.tsx', group: '行政管理', componentKey: 'adminBorrowManagement', permissions: ['oa:borrow:list'] },
  { path: '/admin/risk-alerts', title: '风险预警', source: 'cloudflow-frontend/src/pages/admin/RiskAlertPage.tsx', group: '行政管理', componentKey: 'adminLedger', permissions: ['oa:risk:list'] },
  { path: '/system/dict', title: '字典管理', source: 'cloudflow-frontend/src/pages/admin/DictPage.tsx', group: '系统管理', componentKey: 'systemDict', permissions: ['system:dict:list'] },
  { path: '/workflow/category', title: '流程分类', source: 'cloudflow-frontend/src/pages/admin/ProcessCategoryPage.tsx', group: '工作流', componentKey: 'workflowAdmin', permissions: ['workflow:category:list'] },
  { path: '/workflow/management', title: '流程管理', source: 'cloudflow-frontend/src/pages/admin/ProcessManagement.tsx', group: '工作流', componentKey: 'workflowAdmin', permissions: ['workflow:definition:list'] },
  { path: '/workflow/import', title: '流程导入', source: 'cloudflow-frontend/src/pages/admin/WorkflowImport.tsx', group: '工作流', componentKey: 'workflowAdmin', permissions: ['workflow:import:manage'] },
  { path: '/workflow/archived', title: '归档流程', source: 'cloudflow-frontend/src/pages/admin/ArchivedWorkflows.tsx', group: '工作流', componentKey: 'workflowAdmin', roles: ['ADMIN'] },
  { path: '/workflow/versions/:workflowId', title: '版本历史', source: 'cloudflow-frontend/src/pages/VersionHistoryPage.tsx', group: '工作流', componentKey: 'workflowVersionHistory', permissions: ['workflow:definition:view'] },
  { path: '/templates/manage', title: '模板管理', source: 'cloudflow-frontend/src/pages/admin/TemplateManagement.tsx', group: '工作流', componentKey: 'templateManagement', permissions: ['workflow:template:add'] },
  { path: '/templates', title: '模板库', source: 'cloudflow-frontend/src/pages/TemplateLibrary.tsx', group: '流程中心', componentKey: 'processCenter', permissions: ['workflow:template:list'] },
  { path: '/hr', title: 'HR 首页', source: 'redirect:/hr/dashboard', group: 'HR 人事', componentKey: 'hrDashboard', redirect: '/hr/dashboard' },
  { path: '/hr/dashboard', title: 'HR 看板', source: 'cloudflow-frontend/src/pages/hr/HrDashboardPage.tsx', group: 'HR 人事', componentKey: 'hrDashboard', permissions: ['hr:dashboard:view'] },
  { path: '/hr/employees', title: '员工档案', source: 'cloudflow-frontend/src/pages/hr/HrEmployeePage.tsx', group: 'HR 人事', componentKey: 'hrEmployee', permissions: ['hr:employees:list'] },
  { path: '/hr/organization', title: '组织基础配置', source: 'cloudflow-frontend/src/pages/hr/HrOrganizationPage.tsx', group: 'HR 人事', componentKey: 'hrOrganization', permissions: ['hr:organization:list'] },
  { path: '/hr/recruitment', title: '招聘管理', source: 'cloudflow-frontend/src/pages/hr/HrRecruitmentPage.tsx', group: 'HR 人事', componentKey: 'hrRecruitment', permissions: ['hr:recruitment:list'] },
  { path: '/hr/headcount', title: '编制管理', source: 'cloudflow-frontend/src/pages/hr/HrHeadcountPage.tsx', group: 'HR 人事', componentKey: 'hrHeadcount' },
  { path: '/hr/schedule', title: '排班计划', source: 'cloudflow-backend/cloudflow-service-hr/src/main/java/com/cloudflow/hr/controller/ScheduleController.java', group: 'HR 人事', componentKey: 'hrSchedule' },
  { path: '/hr/salary', title: '薪酬管理', source: 'cloudflow-frontend/src/pages/hr/HrSalaryPage.tsx', group: 'HR 人事', componentKey: 'hrSalary' },
  { path: '/hr/salary/:pathMatch(.*)*', title: '薪酬管理', source: 'cloudflow-frontend/src/pages/hr/HrSalaryPage.tsx', group: 'HR 人事', componentKey: 'hrSalary' },
  { path: '/hr/salary/items', title: '薪资项目', source: 'cloudflow-frontend/src/pages/hr/HrSalaryPage.tsx', group: 'HR 人事', componentKey: 'hrSalary' },
  { path: '/hr/salary/structures', title: '薪资结构', source: 'cloudflow-frontend/src/pages/hr/HrSalaryPage.tsx', group: 'HR 人事', componentKey: 'hrSalary' },
  { path: '/hr/salary/grades', title: '薪资等级', source: 'cloudflow-frontend/src/pages/hr/HrSalaryPage.tsx', group: 'HR 人事', componentKey: 'hrSalary' },
  { path: '/hr/salary/insurance', title: '社保方案', source: 'cloudflow-frontend/src/pages/hr/HrSalaryPage.tsx', group: 'HR 人事', componentKey: 'hrSalary' },
  { path: '/hr/performance', title: '绩效管理', source: 'cloudflow-frontend/src/pages/hr/HrPerformancePage.tsx', group: 'HR 人事', componentKey: 'hrPerformance', permissions: ['hr:performance:list'] },
  { path: '/hr/leave/quota', title: '假期额度', source: 'cloudflow-frontend/src/pages/hr/HrLeaveQuotaPage.tsx', group: 'HR 人事', componentKey: 'hrLeaveQuota' },
  { path: '/hr/onboarding', title: '入职管理', source: 'cloudflow-frontend/src/pages/hr/HrOnboardingPage.tsx', group: 'HR 人事', componentKey: 'hrLifecycle' },
  { path: '/hr/probation', title: '转正管理', source: 'cloudflow-frontend/src/pages/hr/HrProbationPage.tsx', group: 'HR 人事', componentKey: 'hrLifecycle' },
  { path: '/hr/offer', title: 'Offer 管理', source: 'cloudflow-frontend/src/pages/hr/HrOfferPage.tsx', group: 'HR 人事', componentKey: 'hrOffer' },
  { path: '/hr/transfer', title: '调动管理', source: 'cloudflow-frontend/src/pages/hr/HrTransferPage.tsx', group: 'HR 人事', componentKey: 'hrLifecycle' },
  { path: '/hr/resignation', title: '离职管理', source: 'cloudflow-frontend/src/pages/hr/HrResignationPage.tsx', group: 'HR 人事', componentKey: 'hrLifecycle' },
  { path: '/office/meeting-minutes', title: '会议纪要', source: 'cloudflow-frontend/src/pages/MeetingMinutesPage.tsx', group: 'OA 办公', componentKey: 'oaBusiness', permissions: ['oa:meeting:list'] },
  { path: '/office/project', title: '项目管理', source: 'cloudflow-frontend/src/pages/ProjectManagementPage.tsx', group: '项目管理', componentKey: 'oaBusiness', permissions: ['oa:project:list'] },
  { path: '/admin/project-wbs', title: '项目 WBS', source: 'cloudflow-frontend/src/pages/ProjectManagementPage.tsx', group: '项目管理', componentKey: 'oaBusiness', permissions: ['oa:project:wbs'] },
  { path: '/office/budget', title: '预算管理', source: 'cloudflow-frontend/src/pages/BudgetManagementPage.tsx', group: '财务管理', componentKey: 'oaBusiness', permissions: ['oa:budget:list'] },
  { path: '/office/invoice', title: '发票管理', source: 'cloudflow-frontend/src/pages/InvoiceManagementPage.tsx', group: '财务管理', componentKey: 'oaBusiness', permissions: ['oa:invoice:list'] },
  { path: '/office/crm', title: 'CRM 工作台', source: 'cloudflow-frontend/src/pages/CrmManagementPage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:dashboard:view', 'crm:customer:list', 'crm:opportunity:list', 'crm:quote:list', 'crm:receivable:list', 'crm:renewal:list', 'crm:ticket:list'] },
  { path: '/office/crm/customers', title: '客户管理', source: 'cloudflow-frontend/src/pages/CrmManagementPage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:dashboard:view', 'crm:customer:list', 'crm:opportunity:list', 'crm:quote:list', 'crm:receivable:list', 'crm:renewal:list', 'crm:ticket:list'] },
  { path: '/office/crm/opportunities', title: '商机管理', source: 'cloudflow-frontend/src/pages/CrmManagementPage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:dashboard:view', 'crm:customer:list', 'crm:opportunity:list', 'crm:quote:list', 'crm:receivable:list', 'crm:renewal:list', 'crm:ticket:list'] },
  { path: '/office/crm/quotes', title: '报价管理', source: 'cloudflow-frontend/src/pages/CrmManagementPage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:dashboard:view', 'crm:customer:list', 'crm:opportunity:list', 'crm:quote:list', 'crm:receivable:list', 'crm:renewal:list', 'crm:ticket:list'] },
  { path: '/office/crm/receivables', title: '应收管理', source: 'cloudflow-frontend/src/pages/CrmManagementPage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:dashboard:view', 'crm:customer:list', 'crm:opportunity:list', 'crm:quote:list', 'crm:receivable:list', 'crm:renewal:list', 'crm:ticket:list'] },
  { path: '/office/crm/renewals', title: '续约管理', source: 'cloudflow-frontend/src/pages/CrmManagementPage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:dashboard:view', 'crm:customer:list', 'crm:opportunity:list', 'crm:quote:list', 'crm:receivable:list', 'crm:renewal:list', 'crm:ticket:list'] },
  { path: '/office/crm/tickets', title: '服务工单', source: 'cloudflow-frontend/src/pages/CrmManagementPage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:dashboard:view', 'crm:customer:list', 'crm:opportunity:list', 'crm:quote:list', 'crm:receivable:list', 'crm:renewal:list', 'crm:ticket:list'] },
  { path: '/office/crm/leads', title: '线索管理', source: 'cloudflow-frontend/src/pages/CrmLeadPage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:lead:list'] },
  { path: '/office/crm/products', title: '产品管理', source: 'cloudflow-frontend/src/pages/CrmProductPage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:product:list'] },
  { path: '/office/crm/price-books', title: '价目表', source: 'cloudflow-frontend/src/pages/CrmPriceBookPage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:price-book:list'] },
  { path: '/office/crm/sales-targets', title: '销售目标', source: 'cloudflow-frontend/src/pages/CrmSalesTargetPage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:sales-target:list'] },
  { path: '/office/crm/customer-pool', title: '客户公海', source: 'cloudflow-frontend/src/pages/CrmCustomerPoolPage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:customer-pool:list'] },
  { path: '/office/crm/assignment-rules', title: '分配规则', source: 'cloudflow-frontend/src/pages/CrmAssignmentRulePage.tsx', group: 'CRM', componentKey: 'crmModule', permissions: ['crm:assignment-rule:list'] },
  { path: '/office/crm/customer/:customerId', title: '客户工作台', source: 'cloudflow-frontend/src/pages/CrmCustomerWorkspacePage.tsx', group: 'CRM', componentKey: 'crmCustomerWorkspace', permissions: ['crm:customer:list'] },
  { path: '/hr/lifecycle', title: '人事异动', source: 'cloudflow-frontend/src/pages/hr/HrLifecyclePage.tsx', group: 'HR 人事', componentKey: 'hrLifecycle', permissions: ['hr:lifecycle:list'] },
  { path: '/hr/attendance', title: '考勤记录', source: 'cloudflow-frontend/src/pages/hr/HrAttendancePage.tsx', group: 'HR 人事', componentKey: 'hrAdvanced', permissions: ['hr:attendance:list'] },
  { path: '/hr/attendance/appeals', title: '考勤申诉', source: 'cloudflow-frontend/src/pages/hr/HrAttendanceAppealPage.tsx', group: 'HR 人事', componentKey: 'hrAdvanced', permissions: ['hr:attendance:list'] },
  { path: '/hr/compensation', title: '薪酬福利', source: 'cloudflow-frontend/src/pages/hr/HrCompensationPage.tsx', group: 'HR 人事', componentKey: 'hrSalary', permissions: ['hr:compensation:list'] },
  { path: '/hr/ess', title: '员工自助', source: 'cloudflow-frontend/src/pages/hr/HrEssPortalPage.tsx', group: 'HR 员工自助', componentKey: 'hrEss', permissions: ['hr:ess:view'] },
  { path: '/hr/ess/slips', title: '工资条', source: 'cloudflow-frontend/src/pages/hr/ess/HrEssSalarySlipPage.tsx', group: 'HR 员工自助', componentKey: 'hrEss', permissions: ['hr:ess:slip:view'] },
  { path: '/hr/ess/certificates', title: '证明申请', source: 'cloudflow-frontend/src/pages/hr/ess/HrEssCertificatePage.tsx', group: 'HR 员工自助', componentKey: 'hrEss', permissions: ['hr:ess:cert:apply'] },
  { path: '/hr/ess/profile', title: '个人信息维护', source: 'cloudflow-frontend/src/pages/hr/ess/HrEssProfilePage.tsx', group: 'HR 员工自助', componentKey: 'hrEss', permissions: ['hr:ess:profile:edit'] },
  { path: '/hr/ess/leave-balance', title: '假期余额', source: 'cloudflow-frontend/src/pages/hr/ess/HrEssLeaveBalancePage.tsx', group: 'HR 员工自助', componentKey: 'hrEss', permissions: ['hr:ess:leave:view'] },
  { path: '/hr/ess/benefit', title: '福利明细', source: 'cloudflow-frontend/src/pages/hr/ess/HrEssBenefitPage.tsx', group: 'HR 员工自助', componentKey: 'hrEss', permissions: ['hr:ess:benefit:view'] },
  { path: '/hr/ess/contract', title: '电子合同', source: 'cloudflow-frontend/src/pages/hr/ess/HrEssContractPage.tsx', group: 'HR 员工自助', componentKey: 'hrEss', permissions: ['hr:ess:contract:sign'] },
  { path: '/hr/training', title: '培训总览', source: 'redirect:/hr/training/plans', group: 'HR 培训', componentKey: 'hrTraining', redirect: '/hr/training/plans' },
  { path: '/hr/training/plans', title: '培训计划', source: 'cloudflow-frontend/src/pages/hr/HrTrainingPlanPage.tsx', group: 'HR 培训', componentKey: 'hrTraining', permissions: ['hr:training:plan:list'] },
  { path: '/hr/training/courses', title: '培训课程', source: 'cloudflow-frontend/src/pages/hr/HrTrainingCoursePage.tsx', group: 'HR 培训', componentKey: 'hrTraining', permissions: ['hr:training:course:list'] },
  { path: '/hr/training/sessions', title: '培训场次', source: 'cloudflow-frontend/src/pages/hr/HrTrainingSessionPage.tsx', group: 'HR 培训', componentKey: 'hrTraining', permissions: ['hr:training:session:list'] },
  { path: '/hr/training/enrollments', title: '培训报名', source: 'cloudflow-frontend/src/pages/hr/HrTrainingEnrollmentPage.tsx', group: 'HR 培训', componentKey: 'hrTraining', permissions: ['hr:training:enroll:list'] },
  { path: '/hr/training/exams', title: '培训考试', source: 'cloudflow-frontend/src/pages/hr/HrTrainingExamPage.tsx', group: 'HR 培训', componentKey: 'hrTraining', permissions: ['hr:training:exam:list'] },
  { path: '/hr/training/certificates', title: '培训证书', source: 'cloudflow-frontend/src/pages/hr/HrTrainingCertificatePage.tsx', group: 'HR 培训', componentKey: 'hrTraining', permissions: ['hr:training:cert:list'] },
  { path: '/hr/training/archive', title: '培训档案', source: 'cloudflow-frontend/src/pages/hr/HrTrainingArchivePage.tsx', group: 'HR 培训', componentKey: 'hrTraining', permissions: ['hr:training:archive:view'] },
  { path: '/hr/talent', title: '人才盘点', source: 'cloudflow-frontend/src/pages/hr/talent/HrTalentDashboardPage.tsx', group: 'HR 人才', componentKey: 'hrTalent', permissions: ['hr:talent:view'] },
  { path: '/hr/talent/reviews', title: '盘点活动', source: 'cloudflow-frontend/src/pages/hr/talent/HrTalentReviewPage.tsx', group: 'HR 人才', componentKey: 'hrTalent', permissions: ['hr:talent:review:list'] },
  { path: '/hr/talent/nine-box', title: '九宫格校准', source: 'cloudflow-frontend/src/pages/hr/talent/HrTalentNineBoxPage.tsx', group: 'HR 人才', componentKey: 'hrTalent', permissions: ['hr:talent:review:calibrate'] },
  { path: '/hr/talent/calibration', title: '校准会议', source: 'cloudflow-frontend/src/pages/hr/talent/HrTalentCalibrationPage.tsx', group: 'HR 人才', componentKey: 'hrTalent', permissions: ['hr:talent:review:session'] },
  { path: '/hr/talent/succession', title: '继任计划', source: 'cloudflow-frontend/src/pages/hr/talent/HrTalentSuccessionPage.tsx', group: 'HR 人才', componentKey: 'hrTalent', permissions: ['hr:talent:succession:list'] },
  { path: '/hr/talent/pools', title: '人才池', source: 'cloudflow-frontend/src/pages/hr/talent/HrTalentPoolPage.tsx', group: 'HR 人才', componentKey: 'hrTalent', permissions: ['hr:talent:pool:list'] },
  { path: '/hr/talent/development', title: '培养行动', source: 'cloudflow-frontend/src/pages/hr/talent/HrTalentDevelopmentPage.tsx', group: 'HR 人才', componentKey: 'hrTalent', permissions: ['hr:talent:dev:list'] },
  { path: '/hr/talent/archive', title: '人才档案', source: 'cloudflow-frontend/src/pages/hr/talent/HrTalentArchivePage.tsx', group: 'HR 人才', componentKey: 'hrTalent', permissions: ['hr:talent:archive:view', 'hr:talent:archive:mine'] },
  { path: '/hr/benefit', title: '福利积分', source: 'redirect:/hr/benefit/mine', group: 'HR 福利', componentKey: 'hrBenefit', redirect: '/hr/benefit/mine' },
  { path: '/hr/benefit/mine', title: '我的福利', source: 'cloudflow-frontend/src/pages/hr/benefit/HrBenefitMinePage.tsx', group: 'HR 福利', componentKey: 'hrBenefit', permissions: ['hr:benefit:mine'] },
  { path: '/hr/benefit/requests', title: '福利申请', source: 'cloudflow-frontend/src/pages/hr/benefit/HrBenefitRequestPage.tsx', group: 'HR 福利', componentKey: 'hrBenefit', permissions: ['hr:benefit:request:list'] },
  { path: '/hr/benefit/points', title: '积分账户', source: 'cloudflow-frontend/src/pages/hr/benefit/HrPointAccountPage.tsx', group: 'HR 福利', componentKey: 'hrBenefit', permissions: ['hr:benefit:point:view'] },
  { path: '/hr/benefit/mall', title: '福利商城', source: 'cloudflow-frontend/src/pages/hr/benefit/HrMallPage.tsx', group: 'HR 福利', componentKey: 'hrBenefit', permissions: ['hr:benefit:mall:browse'] },
  { path: '/hr/benefit/orders', title: '福利订单', source: 'cloudflow-frontend/src/pages/hr/benefit/HrMallOrderPage.tsx', group: 'HR 福利', componentKey: 'hrBenefit', permissions: ['hr:benefit:order:list'] },
  { path: '/hr/benefit/mall/admin', title: '商品管理', source: 'cloudflow-frontend/src/pages/hr/benefit/HrMallItemAdminPage.tsx', group: 'HR 福利', componentKey: 'hrBenefit', permissions: ['hr:benefit:mall:item-manage'] },
  { path: '/hr/work-injury', title: '工伤管理', source: 'redirect:/hr/work-injury/list', group: 'HR 劳动关系', componentKey: 'hrWorkInjury', redirect: '/hr/work-injury/list' },
  { path: '/hr/work-injury/list', title: '工伤台账', source: 'cloudflow-frontend/src/pages/hr/laborRelation/HrWorkInjuryPage.tsx', group: 'HR 劳动关系', componentKey: 'hrWorkInjury', permissions: ['hr:injury:list'] },
  { path: '/hr/work-injury/investigations', title: '工伤调查', source: 'cloudflow-frontend/src/pages/hr/laborRelation/HrWorkInjuryInvestigationPage.tsx', group: 'HR 劳动关系', componentKey: 'hrWorkInjury', permissions: ['hr:injury:investigate'] },
  { path: '/hr/work-injury/treatments', title: '工伤治疗', source: 'cloudflow-frontend/src/pages/hr/laborRelation/HrWorkInjuryTreatmentPage.tsx', group: 'HR 劳动关系', componentKey: 'hrWorkInjury', permissions: ['hr:injury:treatment'] },
  { path: '/hr/work-injury/compensations', title: '工伤赔付', source: 'cloudflow-frontend/src/pages/hr/laborRelation/HrWorkInjuryCompensationPage.tsx', group: 'HR 劳动关系', componentKey: 'hrWorkInjury', permissions: ['hr:injury:compensation'] },
  { path: '/hr/work-injury/rehabilitation', title: '工伤康复', source: 'cloudflow-frontend/src/pages/hr/laborRelation/HrWorkInjuryRehabilitationPage.tsx', group: 'HR 劳动关系', componentKey: 'hrWorkInjury', permissions: ['hr:injury:rehab'] },
  { path: '/hr/labor-dispute', title: '劳动争议', source: 'redirect:/hr/labor-dispute/list', group: 'HR 劳动关系', componentKey: 'hrLaborDispute', redirect: '/hr/labor-dispute/list' },
  { path: '/hr/labor-dispute/list', title: '争议台账', source: 'cloudflow-frontend/src/pages/hr/laborRelation/HrLaborDisputePage.tsx', group: 'HR 劳动关系', componentKey: 'hrLaborDispute', permissions: ['hr:dispute:list'] },
  { path: '/hr/labor-dispute/mediations', title: '争议调解', source: 'cloudflow-frontend/src/pages/hr/laborRelation/HrDisputeMediationPage.tsx', group: 'HR 劳动关系', componentKey: 'hrLaborDispute', permissions: ['hr:dispute:mediation'] },
  { path: '/hr/labor-dispute/arbitrations', title: '争议仲裁', source: 'cloudflow-frontend/src/pages/hr/laborRelation/HrDisputeArbitrationPage.tsx', group: 'HR 劳动关系', componentKey: 'hrLaborDispute', permissions: ['hr:dispute:arbitration'] },
  { path: '/system/rules', title: '业务规则', source: 'cloudflow-frontend/src/pages/system/BusinessRulePage.tsx', group: '系统安全', componentKey: 'systemSecurity', permissions: ['system:rule:list'] },
  { path: '/system/audit-events', title: '审计事件', source: 'cloudflow-frontend/src/pages/system/AuditEventPage.tsx', group: '系统安全', componentKey: 'systemSecurity', permissions: ['system:audit:events'] },
  { path: '/system/api-ratelimit', title: '接口限流', source: 'cloudflow-frontend/src/pages/system/ApiRateLimitPage.tsx', group: '系统安全', componentKey: 'systemSecurity', permissions: ['system:apiRateLimit:list'] },
  { path: '/system/ip-acl', title: 'IP 访问控制', source: 'cloudflow-frontend/src/pages/system/IpAclPage.tsx', group: '系统安全', componentKey: 'systemSecurity', permissions: ['system:ipAcl:list'] },
  { path: '/system/user-blacklist', title: '用户黑名单', source: 'cloudflow-frontend/src/pages/system/UserBlacklistPage.tsx', group: '系统安全', componentKey: 'systemSecurity', permissions: ['system:userBlacklist:list'] },
  { path: '/oa/contract-threshold', title: '合同金额阈值', source: 'cloudflow-frontend/src/pages/oa/ContractThresholdPage.tsx', group: 'OA 办公', componentKey: 'oaBusiness', permissions: ['oa:contract:threshold:list'] },
  { path: '/system/post', title: '岗位管理', source: 'cloudflow-frontend/src/pages/system/PostList.tsx', group: '系统管理', componentKey: 'systemPost', permissions: ['system:post:list'] },
  { path: '/system/config', title: '参数配置', source: 'cloudflow-frontend/src/pages/system/ConfigList.tsx', group: '系统管理', componentKey: 'systemConfig', permissions: ['system:config:list'] },
  { path: '/system/cache', title: '缓存监控', source: 'cloudflow-frontend/src/pages/system/CacheMonitor.tsx', group: '系统管理', componentKey: 'systemCache', permissions: ['system:cache:list'] }
]

export const mobileRouteCatalog: CloudFlowRouteMeta[] = [
  { path: '/', title: '移动首页', source: 'cloudflow-frontend/src/mobile/pages/MobileDashboard.tsx', group: '移动端', componentKey: 'mobileDashboard', mobile: true },
  { path: '/dashboard', title: '移动首页', source: 'cloudflow-frontend/src/mobile/pages/MobileDashboard.tsx', group: '移动端', componentKey: 'mobileDashboard', mobile: true },
  { path: '/vehicle/booking', title: '移动用车', source: 'cloudflow-frontend/src/mobile/pages/vehicle/MobileVehicleBooking.tsx', group: '移动端', componentKey: 'mobileVehicleBooking', mobile: true },
  { path: '/profile', title: '移动我的', source: 'cloudflow-frontend/src/mobile/pages/MobileProfile.tsx', group: '移动端', componentKey: 'mobileProfile', mobile: true },
  { path: '/messages', title: '移动消息', source: 'cloudflow-frontend/src/mobile/pages/MobileMessages.tsx', group: '移动端', componentKey: 'mobileMessages', mobile: true },
  { path: '/tasks', title: '移动任务', source: 'cloudflow-frontend/src/mobile/pages/MobileTasks.tsx', group: '移动端', componentKey: 'mobileTasks', mobile: true },
  { path: '/schedule', title: '移动日程', source: 'cloudflow-frontend/src/mobile/pages/MobileSchedule.tsx', group: '移动端', componentKey: 'mobileSchedule', mobile: true },
  { path: '/meeting-room', title: '移动会议室', source: 'cloudflow-frontend/src/mobile/pages/MobileMeetingRoom.tsx', group: '移动端', componentKey: 'mobileMeetingRoom', mobile: true },
  { path: '/hr/leave/application', title: '移动请假', source: 'cloudflow-frontend/src/mobile/pages/MobileLeaveApplication.tsx', group: '移动端', componentKey: 'mobileLeaveApplication', mobile: true },
  { path: '/reimbursement/request', title: '移动报销', source: 'cloudflow-frontend/src/mobile/pages/MobileReimbursement.tsx', group: '移动端', componentKey: 'mobileReimbursement', mobile: true },
  { path: '/workflow/monitor', title: '移动流程监控', source: 'cloudflow-frontend/src/mobile/pages/MobileWorkflowMonitor.tsx', group: '移动端', componentKey: 'mobileWorkflowMonitor', mobile: true }
]

export const allRouteCatalog = [...desktopRouteCatalog, ...mobileRouteCatalog]
