export interface CloudFlowRouteMeta {
  path: string
  title: string
  source: string
  group: string
  mobile?: boolean
  public?: boolean
  redirect?: string
  permissions?: string[]
  roles?: string[]
}

export const desktopRouteCatalog: CloudFlowRouteMeta[] = [
  { path: '/', title: '仪表盘', source: 'cloudflow-frontend/src/pages/Dashboard.tsx', group: '工作台' },
  { path: '/dashboard', title: '仪表盘', source: 'cloudflow-frontend/src/pages/Dashboard.tsx', group: '工作台' },
  { path: '/workplace', title: '发起流程', source: 'cloudflow-frontend/src/pages/Workplace.tsx', group: '流程中心', permissions: ['workflow:process:start'] },
  { path: '/profile', title: '个人资料', source: 'cloudflow-frontend/src/pages/ProfilePage.tsx', group: '工作台', permissions: ['system:user:profile:view'] },
  { path: '/tasks', title: '审批待办', source: 'cloudflow-frontend/src/pages/TaskListPage.tsx', group: '流程中心', permissions: ['workflow:task:todo'] },
  { path: '/announcement', title: '公告消息', source: 'cloudflow-frontend/src/pages/AnnouncementPage.tsx', group: '工作台', permissions: ['oa:announcement:list'] },
  { path: '/office/announcement', title: '办公公告', source: 'cloudflow-frontend/src/pages/AnnouncementPage.tsx', group: 'OA 办公', permissions: ['oa:announcement:list'] },
  { path: '/schedule', title: '日程管理', source: 'cloudflow-frontend/src/pages/SchedulePage.tsx', group: 'OA 办公', permissions: ['oa:schedule:list'] },
  { path: '/meeting-room', title: '会议室', source: 'cloudflow-frontend/src/pages/MeetingRoomPage.tsx', group: 'OA 办公', permissions: ['oa:meeting-room:list'] },
  { path: '/my-apps', title: '我的申请', source: 'cloudflow-frontend/src/pages/TaskListPage.tsx', group: '流程中心', permissions: ['workflow:process:mine'] },
  { path: '/my-copies', title: '抄送我的', source: 'cloudflow-frontend/src/pages/CopyListPage.tsx', group: '流程中心', permissions: ['workflow:copy:list'] },
  { path: '/workflow', title: '发起流程', source: 'cloudflow-frontend/src/pages/WorkflowCreate.tsx', group: '工作流', permissions: ['workflow:process:start'] },
  { path: '/workflow/create', title: '发起流程', source: 'cloudflow-frontend/src/pages/WorkflowCreate.tsx', group: '工作流', permissions: ['workflow:process:start'] },
  { path: '/workflow/design', title: '流程设计', source: 'cloudflow-frontend/src/pages/WorkflowDesign.tsx', group: '工作流', permissions: ['workflow:definition:list'] },
  { path: '/workflow/monitor', title: '流程监控', source: 'cloudflow-frontend/src/pages/WorkflowMonitor.tsx', group: '工作流', permissions: ['workflow:monitor:list'] },
  { path: '/workflow/deploy', title: '部署管理', source: 'cloudflow-frontend/src/pages/DeployManagement.tsx', group: '工作流', permissions: ['workflow:deploy:list'] },
  { path: '/workflow/alerts', title: '流程预警', source: 'cloudflow-frontend/src/pages/AlertList.tsx', group: '工作流', permissions: ['workflow:alert:list'] },
  { path: '/workflow/performance', title: '性能统计', source: 'cloudflow-frontend/src/pages/PerformanceStats.tsx', group: '工作流', permissions: ['workflow:performance:view'] },
  { path: '/forms', title: '表单设计', source: 'cloudflow-frontend/src/pages/FormDesign.tsx', group: '工作流', permissions: ['workflow:form:list'] },
  { path: '/users', title: '组织架构', source: 'cloudflow-frontend/src/pages/OrgStructurePage.tsx', group: '系统管理', permissions: ['system:dept:list'] },
  { path: '/code', title: '代码生成', source: 'cloudflow-frontend/src/pages/CodeGeneration.tsx', group: '系统管理', permissions: ['system:code:list'] },
  { path: '/system/users', title: '用户管理', source: 'cloudflow-frontend/src/pages/system/UserList.tsx', group: '系统管理', permissions: ['system:user:list'] },
  { path: '/system/roles', title: '角色管理', source: 'cloudflow-frontend/src/pages/system/RoleList.tsx', group: '系统管理', permissions: ['system:role:list'] },
  { path: '/system/menus', title: '菜单管理', source: 'cloudflow-frontend/src/pages/system/MenuList.tsx', group: '系统管理', permissions: ['system:menu:list'] },
  { path: '/system/files', title: '文件管理', source: 'cloudflow-frontend/src/pages/system/FileList.tsx', group: '系统管理', permissions: ['system:file:list'] },
  { path: '/system/tenant', title: '租户管理', source: 'cloudflow-frontend/src/pages/system/TenantList.tsx', group: '系统管理', permissions: ['system:tenant:list'] },
  { path: '/hr/attendance/checkin', title: '考勤打卡', source: 'cloudflow-frontend/src/pages/admin/attendance/AttendanceCheckIn.tsx', group: 'HR 人事' },
  { path: '/hr/attendance/rule', title: '考勤规则', source: 'cloudflow-frontend/src/pages/admin/attendance/AttendanceRule.tsx', group: 'HR 人事' },
  { path: '/hr/attendance/statistics', title: '考勤统计', source: 'cloudflow-frontend/src/pages/admin/attendance/AttendanceStatisticsPage.tsx', group: 'HR 人事' },
  { path: '/admin/asset', title: '资产管理', source: 'cloudflow-frontend/src/pages/admin/asset/AssetList.tsx', group: '行政管理', permissions: ['oa:asset:list'] },
  { path: '/admin/vehicle', title: '车辆管理', source: 'redirect:/admin/vehicle/list', group: '行政管理', redirect: '/admin/vehicle/list' },
  { path: '/admin/vehicle/list', title: '车辆列表', source: 'cloudflow-frontend/src/pages/admin/vehicle/VehicleList.tsx', group: '行政管理', permissions: ['oa:vehicle:list'] },
  { path: '/admin/vehicle/booking', title: '用车申请', source: 'cloudflow-frontend/src/pages/admin/vehicle/VehicleBooking.tsx', group: '行政管理', permissions: ['oa:vehicle:booking'] },
  { path: '/admin/vehicle/usage', title: '车辆使用', source: 'cloudflow-frontend/src/pages/admin/vehicle/VehicleUsageList.tsx', group: '行政管理', permissions: ['oa:vehicle:usage'] },
  { path: '/expense/claim', title: '费用报销', source: 'cloudflow-frontend/src/pages/ExpenseClaimPage.tsx', group: '财务管理', permissions: ['oa:expense:list'] },
  { path: '/payment/request', title: '付款申请', source: 'cloudflow-frontend/src/pages/PaymentRequestPage.tsx', group: '财务管理', permissions: ['oa:payment:list'] },
  { path: '/office/purchase-request', title: '采购申请', source: 'cloudflow-frontend/src/pages/PurchaseRequestPage.tsx', group: 'OA 办公', permissions: ['oa:purchase:list'] },
  { path: '/office/seal-application', title: '用印申请', source: 'cloudflow-frontend/src/pages/SealApplicationPage.tsx', group: 'OA 办公', permissions: ['oa:seal:list'] },
  { path: '/office/license-borrow', title: '证照借用', source: 'cloudflow-frontend/src/pages/LicenseBorrowPage.tsx', group: 'OA 办公', permissions: ['oa:license:list'] },
  { path: '/office/contracts', title: '合同管理', source: 'cloudflow-frontend/src/pages/ContractPage.tsx', group: 'OA 办公', permissions: ['oa:contract:list'] },
  { path: '/system/log', title: '操作日志', source: 'cloudflow-frontend/src/pages/system/OperationLogPage.tsx', group: '系统管理', permissions: ['system:log:list'] },
  { path: '/system/audit-log', title: '审计日志', source: 'cloudflow-frontend/src/pages/system/AuditLogPage.tsx', group: '系统管理', permissions: ['system:audit:list'] },
  { path: '/system/login-log', title: '登录日志', source: 'cloudflow-frontend/src/pages/system/LoginLogPage.tsx', group: '系统管理', permissions: ['system:login-log:list'] },
  { path: '/system/online', title: '在线用户', source: 'cloudflow-frontend/src/pages/system/OnlineUserPage.tsx', group: '系统管理', permissions: ['system:online:list'] },
  { path: '/hr/attendance/supplement', title: '补卡申请', source: 'cloudflow-frontend/src/pages/AttendanceSupplementPage.tsx', group: 'HR 人事' },
  { path: '/hr/overtime/applications', title: '加班申请', source: 'cloudflow-frontend/src/pages/OvertimeApplicationPage.tsx', group: 'HR 人事' },
  { path: '/hr/leave/application', title: '请假申请', source: 'cloudflow-frontend/src/pages/LeaveApplicationPage.tsx', group: 'HR 人事' },
  { path: '/office/business-trip', title: '出差申请', source: 'cloudflow-frontend/src/pages/BusinessTripPage.tsx', group: 'OA 办公', permissions: ['oa:trip:list'] },
  { path: '/office/contact', title: '通讯录', source: 'cloudflow-frontend/src/pages/ContactPage.tsx', group: 'OA 办公', permissions: ['oa:contact:list'] },
  { path: '/office/knowledge', title: '知识库', source: 'cloudflow-frontend/src/pages/KnowledgePage.tsx', group: 'OA 办公', permissions: ['oa:knowledge:list'] },
  { path: '/admin/visitor', title: '访客管理', source: 'cloudflow-frontend/src/pages/VisitorPage.tsx', group: '行政管理', permissions: ['oa:visitor:list'] },
  { path: '/admin/duty-schedule', title: '值班排班', source: 'cloudflow-frontend/src/pages/DutySchedulePage.tsx', group: '行政管理', permissions: ['oa:duty:list'] },
  { path: '/admin/supplier', title: '供应商', source: 'cloudflow-frontend/src/pages/admin/supplier/SupplierPage.tsx', group: '行政管理', permissions: ['oa:supplier:list'] },
  { path: '/admin/consumable', title: '耗材管理', source: 'cloudflow-frontend/src/pages/admin/consumable/ConsumablePage.tsx', group: '行政管理', permissions: ['oa:consumable:list'] },
  { path: '/admin/seal', title: '印章管理', source: 'cloudflow-frontend/src/pages/admin/seal-license/SealListPage.tsx', group: '行政管理', permissions: ['oa:seal:list'] },
  { path: '/admin/license', title: '证照管理', source: 'cloudflow-frontend/src/pages/admin/seal-license/LicenseListPage.tsx', group: '行政管理', permissions: ['oa:license:list'] },
  { path: '/admin/borrow-management', title: '借用管理', source: 'cloudflow-frontend/src/pages/admin/seal-license/BorrowManagementPage.tsx', group: '行政管理', permissions: ['oa:borrow:list'] },
  { path: '/admin/risk-alerts', title: '风险预警', source: 'cloudflow-frontend/src/pages/admin/RiskAlertPage.tsx', group: '行政管理', permissions: ['oa:risk:list'] },
  { path: '/system/dict', title: '字典管理', source: 'cloudflow-frontend/src/pages/admin/DictPage.tsx', group: '系统管理', permissions: ['system:dict:list'] },
  { path: '/workflow/category', title: '流程分类', source: 'cloudflow-frontend/src/pages/admin/ProcessCategoryPage.tsx', group: '工作流', permissions: ['workflow:category:list'] },
  { path: '/workflow/management', title: '流程管理', source: 'cloudflow-frontend/src/pages/admin/ProcessManagement.tsx', group: '工作流', permissions: ['workflow:definition:list'] },
  { path: '/workflow/import', title: '流程导入', source: 'cloudflow-frontend/src/pages/admin/WorkflowImport.tsx', group: '工作流', permissions: ['workflow:import:manage'] },
  { path: '/workflow/archived', title: '归档流程', source: 'cloudflow-frontend/src/pages/admin/ArchivedWorkflows.tsx', group: '工作流', roles: ['ADMIN'] },
  { path: '/workflow/versions/:workflowId', title: '版本历史', source: 'cloudflow-frontend/src/pages/VersionHistoryPage.tsx', group: '工作流', permissions: ['workflow:definition:view'] },
  { path: '/templates/manage', title: '模板管理', source: 'cloudflow-frontend/src/pages/admin/TemplateManagement.tsx', group: '工作流', permissions: ['workflow:template:add'] },
  { path: '/templates', title: '模板库', source: 'cloudflow-frontend/src/pages/TemplateLibrary.tsx', group: '流程中心', permissions: ['workflow:template:list'] },
  { path: '/hr', title: 'HR 首页', source: 'redirect:/hr/dashboard', group: 'HR 人事', redirect: '/hr/dashboard' },
  { path: '/hr/dashboard', title: 'HR 看板', source: 'cloudflow-frontend/src/pages/hr/HrDashboardPage.tsx', group: 'HR 人事', permissions: ['hr:dashboard:view'] },
  { path: '/hr/employees', title: '员工档案', source: 'cloudflow-frontend/src/pages/hr/HrEmployeePage.tsx', group: 'HR 人事', permissions: ['hr:employees:list'] },
  { path: '/hr/organization', title: '组织基础配置', source: 'cloudflow-frontend/src/pages/hr/HrOrganizationPage.tsx', group: 'HR 人事', permissions: ['hr:organization:list'] },
  { path: '/hr/recruitment', title: '招聘管理', source: 'cloudflow-frontend/src/pages/hr/HrRecruitmentPage.tsx', group: 'HR 人事', permissions: ['hr:recruitment:list'] },
  { path: '/hr/headcount', title: '编制管理', source: 'cloudflow-frontend/src/pages/hr/HrHeadcountPage.tsx', group: 'HR 人事' },
  { path: '/hr/schedule', title: '排班计划', source: 'cloudflow-backend/cloudflow-service-hr/src/main/java/com/cloudflow/hr/controller/ScheduleController.java', group: 'HR 人事' },
  { path: '/hr/salary', title: '薪酬管理', source: 'cloudflow-frontend/src/pages/hr/HrSalaryPage.tsx', group: 'HR 人事' },
  { path: '/hr/salary/:pathMatch(.*)*', title: '薪酬管理', source: 'cloudflow-frontend/src/pages/hr/HrSalaryPage.tsx', group: 'HR 人事' },
  { path: '/hr/salary/items', title: '薪资项目', source: 'cloudflow-frontend/src/pages/hr/HrSalaryPage.tsx', group: 'HR 人事' },
  { path: '/hr/salary/structures', title: '薪资结构', source: 'cloudflow-frontend/src/pages/hr/HrSalaryPage.tsx', group: 'HR 人事' },
  { path: '/hr/salary/grades', title: '薪资等级', source: 'cloudflow-frontend/src/pages/hr/HrSalaryPage.tsx', group: 'HR 人事' },
  { path: '/hr/salary/insurance', title: '社保方案', source: 'cloudflow-frontend/src/pages/hr/HrSalaryPage.tsx', group: 'HR 人事' },
  { path: '/hr/performance', title: '绩效管理', source: 'cloudflow-frontend/src/pages/hr/HrPerformancePage.tsx', group: 'HR 人事', permissions: ['hr:performance:list'] },
  { path: '/hr/leave/quota', title: '假期额度', source: 'cloudflow-frontend/src/pages/hr/HrLeaveQuotaPage.tsx', group: 'HR 人事' },
  { path: '/hr/onboarding', title: '入职管理', source: 'cloudflow-frontend/src/pages/hr/HrOnboardingPage.tsx', group: 'HR 人事' },
  { path: '/hr/probation', title: '转正管理', source: 'cloudflow-frontend/src/pages/hr/HrProbationPage.tsx', group: 'HR 人事' },
  { path: '/hr/offer', title: 'Offer 管理', source: 'cloudflow-frontend/src/pages/hr/HrOfferPage.tsx', group: 'HR 人事' },
  { path: '/hr/transfer', title: '调动管理', source: 'cloudflow-frontend/src/pages/hr/HrTransferPage.tsx', group: 'HR 人事' },
  { path: '/hr/resignation', title: '离职管理', source: 'cloudflow-frontend/src/pages/hr/HrResignationPage.tsx', group: 'HR 人事' },
  { path: '/system/post', title: '岗位管理', source: 'cloudflow-frontend/src/pages/system/PostList.tsx', group: '系统管理', permissions: ['system:post:list'] },
  { path: '/system/config', title: '参数配置', source: 'cloudflow-frontend/src/pages/system/ConfigList.tsx', group: '系统管理', permissions: ['system:config:list'] },
  { path: '/system/cache', title: '缓存监控', source: 'cloudflow-frontend/src/pages/system/CacheMonitor.tsx', group: '系统管理', permissions: ['system:cache:list'] }
]

export const mobileRouteCatalog: CloudFlowRouteMeta[] = [
  { path: '/', title: '移动首页', source: 'cloudflow-frontend/src/mobile/pages/MobileDashboard.tsx', group: '移动端', mobile: true },
  { path: '/dashboard', title: '移动首页', source: 'cloudflow-frontend/src/mobile/pages/MobileDashboard.tsx', group: '移动端', mobile: true },
  { path: '/vehicle/booking', title: '移动用车', source: 'cloudflow-frontend/src/mobile/pages/vehicle/MobileVehicleBooking.tsx', group: '移动端', mobile: true },
  { path: '/profile', title: '移动我的', source: 'cloudflow-frontend/src/mobile/pages/MobileProfile.tsx', group: '移动端', mobile: true },
  { path: '/messages', title: '移动消息', source: 'cloudflow-frontend/src/mobile/pages/MobileMessages.tsx', group: '移动端', mobile: true },
  { path: '/tasks', title: '移动任务', source: 'cloudflow-frontend/src/mobile/pages/MobileTasks.tsx', group: '移动端', mobile: true },
  { path: '/schedule', title: '移动日程', source: 'cloudflow-frontend/src/mobile/pages/MobileSchedule.tsx', group: '移动端', mobile: true },
  { path: '/meeting-room', title: '移动会议室', source: 'cloudflow-frontend/src/mobile/pages/MobileMeetingRoom.tsx', group: '移动端', mobile: true },
  { path: '/hr/leave/application', title: '移动请假', source: 'cloudflow-frontend/src/mobile/pages/MobileLeaveApplication.tsx', group: '移动端', mobile: true },
  { path: '/reimbursement/request', title: '移动报销', source: 'cloudflow-frontend/src/mobile/pages/MobileReimbursement.tsx', group: '移动端', mobile: true },
  { path: '/workflow/monitor', title: '移动流程监控', source: 'cloudflow-frontend/src/mobile/pages/MobileWorkflowMonitor.tsx', group: '移动端', mobile: true }
]

export const allRouteCatalog = [...desktopRouteCatalog, ...mobileRouteCatalog]
