-- =========================================================
-- CloudFlow Pro - CRM 模块数据库脚本
-- 模块：客户、联系人、跟进、商机、报价、回款、续约、工单
-- 版本：v1.0
-- 创建日期：2026-05-07
-- =========================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS crm_lead;
CREATE TABLE crm_lead (
  lead_id            BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '线索ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  lead_no            VARCHAR(50)     NOT NULL COMMENT '线索编号',
  lead_name          VARCHAR(120)    NOT NULL COMMENT '线索名称',
  company_name       VARCHAR(120)    DEFAULT NULL COMMENT '公司名称',
  contact_name       VARCHAR(64)     DEFAULT NULL COMMENT '联系人姓名',
  mobile             VARCHAR(30)     DEFAULT NULL COMMENT '手机号',
  phone              VARCHAR(30)     DEFAULT NULL COMMENT '联系电话',
  email              VARCHAR(100)    DEFAULT NULL COMMENT '联系邮箱',
  source             VARCHAR(30)     DEFAULT NULL COMMENT '线索来源',
  industry           VARCHAR(64)     DEFAULT NULL COMMENT '行业',
  status             VARCHAR(20)     DEFAULT 'NEW' COMMENT '线索状态',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  dept_id            BIGINT(20)      DEFAULT NULL COMMENT '部门ID',
  dept_name          VARCHAR(64)     DEFAULT NULL COMMENT '部门名称',
  next_follow_up_time DATETIME       DEFAULT NULL COMMENT '下次跟进时间',
  last_follow_up_time DATETIME       DEFAULT NULL COMMENT '最近跟进时间',
  converted_customer_id BIGINT(20)   DEFAULT NULL COMMENT '转化后的客户ID',
  converted_time     DATETIME        DEFAULT NULL COMMENT '转化时间',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (lead_id),
  UNIQUE KEY uk_crm_lead_no (tenant_id, lead_no),
  KEY idx_crm_lead_owner (tenant_id, owner_id),
  KEY idx_crm_lead_status (tenant_id, status),
  KEY idx_crm_lead_company (tenant_id, company_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM线索表';

DROP TABLE IF EXISTS crm_product;
CREATE TABLE crm_product (
  product_id         BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '产品ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  product_no         VARCHAR(50)     NOT NULL COMMENT '产品编号',
  product_name       VARCHAR(120)    NOT NULL COMMENT '产品名称',
  category           VARCHAR(64)     DEFAULT NULL COMMENT '产品分类',
  spec               VARCHAR(255)    DEFAULT NULL COMMENT '规格型号',
  unit               VARCHAR(30)     DEFAULT NULL COMMENT '单位',
  standard_price     DECIMAL(16,2)   DEFAULT 0.00 COMMENT '标准单价',
  currency           VARCHAR(10)     DEFAULT 'CNY' COMMENT '币种',
  status             VARCHAR(20)     DEFAULT 'ACTIVE' COMMENT '状态',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (product_id),
  UNIQUE KEY uk_crm_product_no (tenant_id, product_no),
  KEY idx_crm_product_name (tenant_id, product_name),
  KEY idx_crm_product_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM产品表';

DROP TABLE IF EXISTS crm_price_book;
CREATE TABLE crm_price_book (
  price_book_id      BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '价目表ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  price_book_no      VARCHAR(50)     NOT NULL COMMENT '价目表编号',
  price_book_name    VARCHAR(120)    NOT NULL COMMENT '价目表名称',
  currency           VARCHAR(10)     DEFAULT 'CNY' COMMENT '币种',
  start_date         DATE            DEFAULT NULL COMMENT '生效开始日期',
  end_date           DATE            DEFAULT NULL COMMENT '生效结束日期',
  status             VARCHAR(20)     DEFAULT 'ACTIVE' COMMENT '状态',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (price_book_id),
  UNIQUE KEY uk_crm_price_book_no (tenant_id, price_book_no),
  KEY idx_crm_price_book_name (tenant_id, price_book_name),
  KEY idx_crm_price_book_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM价目表';

DROP TABLE IF EXISTS crm_quote_line;
CREATE TABLE crm_quote_line (
  quote_line_id      BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '报价行ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  quote_id           BIGINT(20)      NOT NULL COMMENT '报价ID',
  sort_no            INT(11)         DEFAULT 1 COMMENT '排序号',
  product_id         BIGINT(20)      DEFAULT NULL COMMENT '产品ID',
  product_no         VARCHAR(50)     DEFAULT NULL COMMENT '产品编号快照',
  product_name       VARCHAR(120)    NOT NULL COMMENT '产品名称快照',
  category           VARCHAR(64)     DEFAULT NULL COMMENT '产品分类快照',
  spec               VARCHAR(255)    DEFAULT NULL COMMENT '规格型号快照',
  unit               VARCHAR(30)     DEFAULT NULL COMMENT '单位快照',
  quantity           DECIMAL(16,2)   DEFAULT 1.00 COMMENT '数量',
  unit_price         DECIMAL(16,2)   DEFAULT 0.00 COMMENT '单价',
  discount_rate      DECIMAL(5,2)    DEFAULT 100.00 COMMENT '折扣率',
  tax_rate           DECIMAL(5,2)    DEFAULT 0.00 COMMENT '税率',
  line_amount        DECIMAL(16,2)   DEFAULT 0.00 COMMENT '行金额',
  tax_amount         DECIMAL(16,2)   DEFAULT 0.00 COMMENT '行税额',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (quote_line_id),
  KEY idx_crm_quote_line_quote (tenant_id, quote_id),
  KEY idx_crm_quote_line_product (tenant_id, product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM报价行项目表';

DROP TABLE IF EXISTS crm_sales_target;
CREATE TABLE crm_sales_target (
  sales_target_id     BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '销售目标ID',
  tenant_id           BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  target_no           VARCHAR(50)     NOT NULL COMMENT '目标编号',
  target_name         VARCHAR(120)    NOT NULL COMMENT '目标名称',
  dimension_type      VARCHAR(20)     NOT NULL COMMENT '维度类型：OWNER/DEPT',
  period_type         VARCHAR(20)     NOT NULL COMMENT '周期类型：MONTH/QUARTER/YEAR',
  target_year         INT(11)         NOT NULL COMMENT '目标年份',
  target_period       INT(11)         DEFAULT NULL COMMENT '目标周期值（月1-12 / 季1-4）',
  dept_id             BIGINT(20)      DEFAULT NULL COMMENT '部门ID',
  dept_name           VARCHAR(64)     DEFAULT NULL COMMENT '部门名称',
  owner_id            BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name          VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  target_amount       DECIMAL(16,2)   NOT NULL COMMENT '目标金额',
  status              VARCHAR(20)     DEFAULT 'ACTIVE' COMMENT '状态',
  remark              VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  deleted             TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by           VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time         DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by           VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time         DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (sales_target_id),
  UNIQUE KEY uk_crm_sales_target_no (tenant_id, target_no),
  KEY idx_crm_sales_target_dimension (tenant_id, dimension_type),
  KEY idx_crm_sales_target_period (tenant_id, period_type, target_year, target_period),
  KEY idx_crm_sales_target_owner (tenant_id, owner_id),
  KEY idx_crm_sales_target_dept (tenant_id, dept_id),
  KEY idx_crm_sales_target_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM销售目标与配额表';

DROP TABLE IF EXISTS crm_customer;
CREATE TABLE crm_customer (
  customer_id        BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '客户ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  customer_code      VARCHAR(50)     NOT NULL COMMENT '客户编码',
  customer_name      VARCHAR(120)    NOT NULL COMMENT '客户名称',
  customer_type      VARCHAR(30)     DEFAULT 'ENTERPRISE' COMMENT '客户类型',
  industry           VARCHAR(64)     DEFAULT NULL COMMENT '行业',
  level_code         VARCHAR(20)     DEFAULT 'NORMAL' COMMENT '客户等级',
  source             VARCHAR(30)     DEFAULT NULL COMMENT '客户来源',
  customer_tags      VARCHAR(255)    DEFAULT NULL COMMENT '客户标签，逗号分隔',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  dept_id            BIGINT(20)      DEFAULT NULL COMMENT '所属部门ID',
  dept_name          VARCHAR(64)     DEFAULT NULL COMMENT '所属部门名称',
  phone              VARCHAR(30)     DEFAULT NULL COMMENT '联系电话',
  email              VARCHAR(100)    DEFAULT NULL COMMENT '联系邮箱',
  website            VARCHAR(255)    DEFAULT NULL COMMENT '官网',
  province           VARCHAR(64)     DEFAULT NULL COMMENT '省份',
  city               VARCHAR(64)     DEFAULT NULL COMMENT '城市',
  address            VARCHAR(255)    DEFAULT NULL COMMENT '地址',
  credit_code        VARCHAR(50)     DEFAULT NULL COMMENT '统一社会信用代码',
  health_level       VARCHAR(20)     DEFAULT 'GREEN' COMMENT '健康度等级',
  health_reason      VARCHAR(500)    DEFAULT NULL COMMENT '健康度原因',
  last_follow_up_time DATETIME       DEFAULT NULL COMMENT '最近跟进时间',
  next_follow_up_time DATETIME       DEFAULT NULL COMMENT '下次跟进时间',
  pool_flag          CHAR(1)         DEFAULT '0' COMMENT '是否在公海：0否 1是',
  pooled_time        DATETIME        DEFAULT NULL COMMENT '入池时间',
  original_owner_id  BIGINT(20)      DEFAULT NULL COMMENT '入池前原负责人ID',
  original_owner_name VARCHAR(64)    DEFAULT NULL COMMENT '入池前原负责人姓名',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  status             VARCHAR(20)     DEFAULT 'ACTIVE' COMMENT '状态',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (customer_id),
  UNIQUE KEY uk_crm_customer_code (tenant_id, customer_code),
  KEY idx_crm_customer_owner (tenant_id, owner_id),
  KEY idx_crm_customer_health (tenant_id, health_level),
  KEY idx_crm_customer_name (tenant_id, customer_name),
  KEY idx_crm_customer_pool (tenant_id, pool_flag, last_follow_up_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM客户表';

DROP TABLE IF EXISTS crm_contact;
CREATE TABLE crm_contact (
  contact_id         BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '联系人ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  contact_name       VARCHAR(64)     NOT NULL COMMENT '联系人姓名',
  gender             VARCHAR(10)     DEFAULT NULL COMMENT '性别',
  mobile             VARCHAR(30)     DEFAULT NULL COMMENT '手机号',
  phone              VARCHAR(30)     DEFAULT NULL COMMENT '电话',
  email              VARCHAR(100)    DEFAULT NULL COMMENT '邮箱',
  position           VARCHAR(64)     DEFAULT NULL COMMENT '职位',
  department         VARCHAR(64)     DEFAULT NULL COMMENT '部门',
  primary_flag       TINYINT(1)      DEFAULT 0 COMMENT '是否主联系人',
  wechat             VARCHAR(64)     DEFAULT NULL COMMENT '微信',
  qq                 VARCHAR(32)     DEFAULT NULL COMMENT 'QQ',
  birthday           DATE            DEFAULT NULL COMMENT '生日',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  status             VARCHAR(20)     DEFAULT 'ACTIVE' COMMENT '状态',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (contact_id),
  KEY idx_crm_contact_customer (tenant_id, customer_id),
  KEY idx_crm_contact_name (tenant_id, contact_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM联系人表';

DROP TABLE IF EXISTS crm_follow_up;
CREATE TABLE crm_follow_up (
  follow_up_id       BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '跟进ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  opportunity_id     BIGINT(20)      DEFAULT NULL COMMENT '商机ID',
  follow_up_type     VARCHAR(30)     DEFAULT 'VISIT' COMMENT '跟进类型',
  follow_up_time     DATETIME        NOT NULL COMMENT '跟进时间',
  next_follow_up_time DATETIME       DEFAULT NULL COMMENT '下次跟进时间',
  content            VARCHAR(1000)   NOT NULL COMMENT '跟进内容',
  result_summary     VARCHAR(500)    DEFAULT NULL COMMENT '跟进结果',
  attachment_url     VARCHAR(1000)   DEFAULT NULL COMMENT '附件地址',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '跟进人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '跟进人姓名',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (follow_up_id),
  KEY idx_crm_follow_customer (tenant_id, customer_id),
  KEY idx_crm_follow_opportunity (tenant_id, opportunity_id),
  KEY idx_crm_follow_time (tenant_id, follow_up_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM跟进记录表';

DROP TABLE IF EXISTS crm_opportunity;
CREATE TABLE crm_opportunity (
  opportunity_id     BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '商机ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  customer_name      VARCHAR(120)    DEFAULT NULL COMMENT '客户名称快照',
  opportunity_name   VARCHAR(120)    NOT NULL COMMENT '商机名称',
  stage              VARCHAR(30)     DEFAULT 'LEAD' COMMENT '商机阶段',
  source             VARCHAR(30)     DEFAULT NULL COMMENT '商机来源',
  expected_amount    DECIMAL(16,2)   DEFAULT 0.00 COMMENT '预计金额',
  win_rate           DECIMAL(5,2)    DEFAULT 0.00 COMMENT '赢单率',
  expected_sign_date DATE            DEFAULT NULL COMMENT '预计签约日期',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  dept_id            BIGINT(20)      DEFAULT NULL COMMENT '部门ID',
  dept_name          VARCHAR(64)     DEFAULT NULL COMMENT '部门名称',
  contact_id         BIGINT(20)      DEFAULT NULL COMMENT '主联系人ID',
  contact_name       VARCHAR(64)     DEFAULT NULL COMMENT '主联系人姓名',
  latest_follow_up_time DATETIME     DEFAULT NULL COMMENT '最近跟进时间',
  stage_changed_time DATETIME        DEFAULT NULL COMMENT '阶段更新时间',
  lost_reason        VARCHAR(500)    DEFAULT NULL COMMENT '输单原因',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  status             VARCHAR(20)     DEFAULT 'OPEN' COMMENT '状态',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (opportunity_id),
  KEY idx_crm_opportunity_customer (tenant_id, customer_id),
  KEY idx_crm_opportunity_stage (tenant_id, stage),
  KEY idx_crm_opportunity_owner (tenant_id, owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM商机表';

DROP TABLE IF EXISTS crm_quote;
CREATE TABLE crm_quote (
  quote_id           BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '报价ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  instance_id        VARCHAR(64)     DEFAULT NULL COMMENT '流程实例ID',
  quote_no           VARCHAR(50)     NOT NULL COMMENT '报价单号',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  customer_name      VARCHAR(120)    DEFAULT NULL COMMENT '客户名称快照',
  opportunity_id     BIGINT(20)      DEFAULT NULL COMMENT '商机ID',
  opportunity_name   VARCHAR(120)    DEFAULT NULL COMMENT '商机名称快照',
  quote_name         VARCHAR(120)    NOT NULL COMMENT '报价名称',
  total_amount       DECIMAL(16,2)   NOT NULL COMMENT '报价总金额',
  tax_amount         DECIMAL(16,2)   DEFAULT 0.00 COMMENT '税额',
  currency           VARCHAR(10)     DEFAULT 'CNY' COMMENT '币种',
  valid_until        DATE            DEFAULT NULL COMMENT '有效期',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  contract_id        BIGINT(20)      DEFAULT NULL COMMENT '关联合同ID',
  contract_no        VARCHAR(50)     DEFAULT NULL COMMENT '关联合同编号',
  attachment_url     VARCHAR(1000)   DEFAULT NULL COMMENT '附件地址',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  status             VARCHAR(20)     DEFAULT 'DRAFT' COMMENT '报价状态',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (quote_id),
  UNIQUE KEY uk_crm_quote_no (tenant_id, quote_no),
  KEY idx_crm_quote_customer (tenant_id, customer_id),
  KEY idx_crm_quote_opportunity (tenant_id, opportunity_id),
  KEY idx_crm_quote_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM报价单表';

DROP TABLE IF EXISTS crm_receivable;
CREATE TABLE crm_receivable (
  receivable_id      BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '回款ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  customer_name      VARCHAR(120)    DEFAULT NULL COMMENT '客户名称快照',
  contract_id        BIGINT(20)      DEFAULT NULL COMMENT '合同ID',
  contract_no        VARCHAR(50)     DEFAULT NULL COMMENT '合同编号',
  receivable_no      VARCHAR(50)     NOT NULL COMMENT '回款编号',
  receivable_name    VARCHAR(120)    NOT NULL COMMENT '回款名称',
  planned_amount     DECIMAL(16,2)   NOT NULL COMMENT '计划回款金额',
  received_amount    DECIMAL(16,2)   DEFAULT 0.00 COMMENT '已回款金额',
  outstanding_amount DECIMAL(16,2)   DEFAULT 0.00 COMMENT '未回款金额',
  due_date           DATE            DEFAULT NULL COMMENT '应收日期',
  received_date      DATE            DEFAULT NULL COMMENT '实收日期',
  invoice_status     VARCHAR(20)     DEFAULT 'NONE' COMMENT '发票状态',
  invoice_id         BIGINT(20)      DEFAULT NULL COMMENT '关联 OA 发票ID（反向同步时写入）',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  status             VARCHAR(20)     DEFAULT 'PLANNED' COMMENT '回款状态',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (receivable_id),
  UNIQUE KEY uk_crm_receivable_no (tenant_id, receivable_no),
  KEY idx_crm_receivable_customer (tenant_id, customer_id),
  KEY idx_crm_receivable_contract (tenant_id, contract_id),
  KEY idx_crm_receivable_due (tenant_id, due_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM回款计划表';

DROP TABLE IF EXISTS crm_renewal;
CREATE TABLE crm_renewal (
  renewal_id         BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '续约ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  instance_id        VARCHAR(64)     DEFAULT NULL COMMENT '流程实例ID',
  renewal_no         VARCHAR(50)     NOT NULL COMMENT '续约编号',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  customer_name      VARCHAR(120)    DEFAULT NULL COMMENT '客户名称快照',
  contract_id        BIGINT(20)      DEFAULT NULL COMMENT '关联合同ID',
  contract_no        VARCHAR(50)     DEFAULT NULL COMMENT '关联合同编号',
  renewal_name       VARCHAR(120)    NOT NULL COMMENT '续约名称',
  renewal_amount     DECIMAL(16,2)   DEFAULT 0.00 COMMENT '续约金额',
  expected_sign_date DATE            DEFAULT NULL COMMENT '预计签约日期',
  current_expire_date DATE           DEFAULT NULL COMMENT '当前到期日期',
  next_expire_date   DATE            DEFAULT NULL COMMENT '续约后到期日期',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  summary            VARCHAR(500)    DEFAULT NULL COMMENT '续约摘要',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  status             VARCHAR(20)     DEFAULT 'PLANNED' COMMENT '续约状态',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (renewal_id),
  UNIQUE KEY uk_crm_renewal_no (tenant_id, renewal_no),
  KEY idx_crm_renewal_customer (tenant_id, customer_id),
  KEY idx_crm_renewal_contract (tenant_id, contract_id),
  KEY idx_crm_renewal_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM续约表';

DROP TABLE IF EXISTS crm_service_ticket;
CREATE TABLE crm_service_ticket (
  ticket_id          BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '工单ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  customer_name      VARCHAR(120)    DEFAULT NULL COMMENT '客户名称快照',
  ticket_no          VARCHAR(50)     NOT NULL COMMENT '工单编号',
  ticket_title       VARCHAR(120)    NOT NULL COMMENT '工单标题',
  severity           VARCHAR(20)     DEFAULT 'LOW' COMMENT '严重度',
  issue_type         VARCHAR(30)     DEFAULT 'OTHER' COMMENT '问题类型',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  opened_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  resolved_time      DATETIME        DEFAULT NULL COMMENT '解决时间',
  due_time           DATETIME        DEFAULT NULL COMMENT '截止时间',
  description        VARCHAR(1000)   DEFAULT NULL COMMENT '问题描述',
  solution           VARCHAR(1000)   DEFAULT NULL COMMENT '解决方案',
  attachment_url     VARCHAR(1000)   DEFAULT NULL COMMENT '附件地址',
  status             VARCHAR(20)     DEFAULT 'OPEN' COMMENT '工单状态',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (ticket_id),
  UNIQUE KEY uk_crm_ticket_no (tenant_id, ticket_no),
  KEY idx_crm_ticket_customer (tenant_id, customer_id),
  KEY idx_crm_ticket_status (tenant_id, status),
  KEY idx_crm_ticket_severity (tenant_id, severity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM服务工单表';

-- ============================================================================
-- CRM 客户/商机交接待办（员工离职触发生成）
-- ============================================================================
DROP TABLE IF EXISTS crm_handover_task;
CREATE TABLE crm_handover_task (
  handover_id        BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '交接任务ID',
  tenant_id          BIGINT(20)      NOT NULL DEFAULT 100000 COMMENT '租户ID',
  from_owner_id      BIGINT(20)      NOT NULL COMMENT '原负责人 userId',
  from_owner_name    VARCHAR(80)     DEFAULT NULL COMMENT '原负责人姓名',
  from_dept_id       BIGINT(20)      DEFAULT NULL COMMENT '原部门ID',
  business_type      VARCHAR(30)     NOT NULL COMMENT '业务类型 CRM_CUSTOMER / CRM_OPPORTUNITY',
  business_id        BIGINT(20)      NOT NULL COMMENT '业务ID',
  business_name      VARCHAR(200)    DEFAULT NULL COMMENT '业务名称快照',
  status             VARCHAR(20)     DEFAULT 'PENDING' COMMENT '状态 PENDING / REASSIGNED / CLOSED',
  to_owner_id        BIGINT(20)      DEFAULT NULL COMMENT '新负责人 userId',
  to_owner_name      VARCHAR(80)     DEFAULT NULL COMMENT '新负责人姓名',
  trigger_source     VARCHAR(30)     DEFAULT 'EMPLOYEE_LEFT' COMMENT '触发来源',
  trigger_event_id   VARCHAR(64)     DEFAULT NULL COMMENT 'Redis Stream 记录ID，幂等用',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (handover_id),
  UNIQUE KEY uk_crm_handover_biz (tenant_id, business_type, business_id, from_owner_id, status),
  KEY idx_crm_handover_owner (tenant_id, from_owner_id),
  KEY idx_crm_handover_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM 交接待办';

-- ============================================================================
-- CRM 通用审批流水（承载客户领取/公海释放、商机降级关闭、客户分级变更、退款）
-- ============================================================================
DROP TABLE IF EXISTS crm_approval;
CREATE TABLE crm_approval (
  approval_id        BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '审批ID',
  tenant_id          BIGINT(20)      NOT NULL DEFAULT 100000 COMMENT '租户ID',
  approval_no        VARCHAR(50)     NOT NULL COMMENT '审批编号',
  business_type      VARCHAR(40)     NOT NULL COMMENT '业务类型: crm_customer_claim / crm_customer_level / crm_opportunity_downgrade / crm_refund',
  action_type        VARCHAR(30)     DEFAULT NULL COMMENT '业务动作(CLAIM/RELEASE/DOWNGRADE/CLOSE/LEVEL_UP/LEVEL_DOWN/REFUND)',
  business_ref_type  VARCHAR(30)     DEFAULT NULL COMMENT '业务目标 CRM_CUSTOMER/CRM_OPPORTUNITY/CRM_RECEIVABLE',
  business_ref_id    BIGINT(20)      DEFAULT NULL COMMENT '业务目标ID',
  business_ref_name  VARCHAR(200)    DEFAULT NULL COMMENT '业务目标名称快照',
  payload_json       JSON            DEFAULT NULL COMMENT '申请详情（如调整前/后值、金额等）',
  applicant_id       BIGINT(20)      DEFAULT NULL COMMENT '申请人 userId',
  applicant_name     VARCHAR(80)     DEFAULT NULL COMMENT '申请人姓名',
  dept_id            BIGINT(20)      DEFAULT NULL COMMENT '申请部门',
  dept_name          VARCHAR(80)     DEFAULT NULL COMMENT '申请部门名称',
  status             VARCHAR(20)     DEFAULT 'DRAFT' COMMENT 'DRAFT/PENDING/APPROVED/REJECTED/CANCELLED',
  instance_id        VARCHAR(80)     DEFAULT NULL COMMENT '流程实例ID',
  approval_comment   VARCHAR(500)    DEFAULT NULL COMMENT '审批意见',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  deleted            TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (approval_id),
  UNIQUE KEY uk_crm_approval_no (tenant_id, approval_no),
  KEY idx_crm_approval_business (tenant_id, business_type, business_ref_id),
  KEY idx_crm_approval_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM 通用审批流水';

-- ============================================================================
-- CRM 客户公海操作日志
-- ============================================================================
DROP TABLE IF EXISTS crm_customer_pool_log;
CREATE TABLE crm_customer_pool_log (
  log_id              BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  tenant_id           BIGINT(20)      NOT NULL DEFAULT 100000 COMMENT '租户ID',
  customer_id         BIGINT(20)      NOT NULL COMMENT '客户ID',
  customer_name       VARCHAR(120)    DEFAULT NULL COMMENT '客户名称快照',
  action_type         VARCHAR(30)     NOT NULL COMMENT '动作类型 RELEASE/CLAIM/ASSIGN/AUTO_RELEASE',
  from_owner_id       BIGINT(20)      DEFAULT NULL COMMENT '变更前负责人ID',
  from_owner_name     VARCHAR(80)     DEFAULT NULL COMMENT '变更前负责人姓名',
  to_owner_id         BIGINT(20)      DEFAULT NULL COMMENT '变更后负责人ID',
  to_owner_name       VARCHAR(80)     DEFAULT NULL COMMENT '变更后负责人姓名',
  rule_id             BIGINT(20)      DEFAULT NULL COMMENT '触发规则ID',
  reason              VARCHAR(500)    DEFAULT NULL COMMENT '触发原因/说明',
  deleted             TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  create_by           VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time         DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by           VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time         DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (log_id),
  KEY idx_crm_pool_log_customer (tenant_id, customer_id),
  KEY idx_crm_pool_log_action (tenant_id, action_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM 客户公海操作日志';

-- ============================================================================
-- CRM 客户分配规则（自动回收 + 抢单策略）
-- ============================================================================
DROP TABLE IF EXISTS crm_assignment_rule;
CREATE TABLE crm_assignment_rule (
  rule_id             BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '规则ID',
  tenant_id           BIGINT(20)      NOT NULL DEFAULT 100000 COMMENT '租户ID',
  rule_name           VARCHAR(120)    NOT NULL COMMENT '规则名称',
  rule_type           VARCHAR(30)     NOT NULL COMMENT '规则类型 AUTO_RELEASE/CLAIM_LIMIT/ASSIGN',
  priority            INT(11)         DEFAULT 100 COMMENT '优先级，数字越小越先匹配',
  status              VARCHAR(20)     DEFAULT 'ACTIVE' COMMENT '状态 ACTIVE/INACTIVE',
  inactive_days       INT(11)         DEFAULT NULL COMMENT '连续未跟进天数阈值（AUTO_RELEASE 用）',
  max_per_owner       INT(11)         DEFAULT NULL COMMENT '单人持有上限（CLAIM_LIMIT 用）',
  dept_id             BIGINT(20)      DEFAULT NULL COMMENT '仅对指定部门生效',
  dept_name           VARCHAR(64)     DEFAULT NULL COMMENT '部门名称',
  customer_level      VARCHAR(20)     DEFAULT NULL COMMENT '仅对指定客户等级生效',
  customer_tags       VARCHAR(255)    DEFAULT NULL COMMENT '匹配客户标签（逗号分隔）',
  effective_start     DATE            DEFAULT NULL COMMENT '生效开始日期',
  effective_end       DATE            DEFAULT NULL COMMENT '生效结束日期',
  remark              VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  deleted             TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '逻辑删除(0=未删除 1=已删除)',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by           VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time         DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by           VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time         DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (rule_id),
  KEY idx_crm_assign_rule_type (tenant_id, rule_type, status),
  KEY idx_crm_assign_rule_priority (tenant_id, priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM 客户分配规则';

SET FOREIGN_KEY_CHECKS = 1;
