-- =========================================================
-- CloudFlow Pro - CRM 模块数据库脚本
-- 模块：客户、联系人、跟进、商机、报价、回款、续约、工单
-- 版本：v1.0
-- 创建日期：2026-05-07
-- =========================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS oa_crm_customer;
CREATE TABLE oa_crm_customer (
  customer_id        BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '客户ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  customer_code      VARCHAR(50)     NOT NULL COMMENT '客户编码',
  customer_name      VARCHAR(120)    NOT NULL COMMENT '客户名称',
  customer_type      VARCHAR(30)     DEFAULT 'ENTERPRISE' COMMENT '客户类型',
  industry           VARCHAR(64)     DEFAULT NULL COMMENT '行业',
  level_code         VARCHAR(20)     DEFAULT 'NORMAL' COMMENT '客户等级',
  source             VARCHAR(30)     DEFAULT NULL COMMENT '客户来源',
  customer_tags      VARCHAR(255)    DEFAULT NULL COMMENT '客户标签，逗号分隔',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  dept_id            BIGINT(20)      DEFAULT NULL COMMENT '所属部门ID',
  dept_name          VARCHAR(64)     DEFAULT NULL COMMENT '所属部门名称',
  phone              VARCHAR(30)     DEFAULT NULL COMMENT '联系电话',
  email              VARCHAR(100)    DEFAULT NULL COMMENT '联系邮箱',
  website            VARCHAR(255)    DEFAULT NULL COMMENT '官网',
  province           VARCHAR(64)     DEFAULT NULL COMMENT '省份',
  city               VARCHAR(64)     DEFAULT NULL COMMENT '城市',
  address            VARCHAR(255)    DEFAULT NULL COMMENT '地址',
  credit_code        VARCHAR(50)     DEFAULT NULL COMMENT '统一社会信用代码',
  health_level       VARCHAR(20)     DEFAULT 'GREEN' COMMENT '健康度等级',
  health_reason      VARCHAR(500)    DEFAULT NULL COMMENT '健康度原因',
  last_follow_up_time DATETIME       DEFAULT NULL COMMENT '最近跟进时间',
  next_follow_up_time DATETIME       DEFAULT NULL COMMENT '下次跟进时间',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  status             VARCHAR(20)     DEFAULT 'ACTIVE' COMMENT '状态',
  del_flag           CHAR(1)         DEFAULT '0' COMMENT '删除标志',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (customer_id),
  UNIQUE KEY uk_crm_customer_code (tenant_id, customer_code),
  KEY idx_crm_customer_owner (owner_id),
  KEY idx_crm_customer_health (health_level),
  KEY idx_crm_customer_name (customer_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM客户表';

DROP TABLE IF EXISTS oa_crm_contact;
CREATE TABLE oa_crm_contact (
  contact_id         BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '联系人ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  contact_name       VARCHAR(64)     NOT NULL COMMENT '联系人姓名',
  gender             VARCHAR(10)     DEFAULT NULL COMMENT '性别',
  mobile             VARCHAR(30)     DEFAULT NULL COMMENT '手机号',
  phone              VARCHAR(30)     DEFAULT NULL COMMENT '电话',
  email              VARCHAR(100)    DEFAULT NULL COMMENT '邮箱',
  position           VARCHAR(64)     DEFAULT NULL COMMENT '职位',
  department         VARCHAR(64)     DEFAULT NULL COMMENT '部门',
  primary_flag       TINYINT(1)      DEFAULT 0 COMMENT '是否主联系人',
  wechat             VARCHAR(64)     DEFAULT NULL COMMENT '微信',
  qq                 VARCHAR(32)     DEFAULT NULL COMMENT 'QQ',
  birthday           DATE            DEFAULT NULL COMMENT '生日',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  status             VARCHAR(20)     DEFAULT 'ACTIVE' COMMENT '状态',
  del_flag           CHAR(1)         DEFAULT '0' COMMENT '删除标志',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (contact_id),
  KEY idx_crm_contact_customer (customer_id),
  KEY idx_crm_contact_name (contact_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM联系人表';

DROP TABLE IF EXISTS oa_crm_follow_up;
CREATE TABLE oa_crm_follow_up (
  follow_up_id       BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '跟进ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  opportunity_id     BIGINT(20)      DEFAULT NULL COMMENT '商机ID',
  follow_up_type     VARCHAR(30)     DEFAULT 'VISIT' COMMENT '跟进类型',
  follow_up_time     DATETIME        NOT NULL COMMENT '跟进时间',
  next_follow_up_time DATETIME       DEFAULT NULL COMMENT '下次跟进时间',
  content            VARCHAR(1000)   NOT NULL COMMENT '跟进内容',
  result_summary     VARCHAR(500)    DEFAULT NULL COMMENT '跟进结果',
  attachment_url     VARCHAR(1000)   DEFAULT NULL COMMENT '附件地址',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '跟进人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '跟进人姓名',
  del_flag           CHAR(1)         DEFAULT '0' COMMENT '删除标志',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (follow_up_id),
  KEY idx_crm_follow_customer (customer_id),
  KEY idx_crm_follow_opportunity (opportunity_id),
  KEY idx_crm_follow_time (follow_up_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM跟进记录表';

DROP TABLE IF EXISTS oa_crm_opportunity;
CREATE TABLE oa_crm_opportunity (
  opportunity_id     BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '商机ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  customer_name      VARCHAR(120)    DEFAULT NULL COMMENT '客户名称快照',
  opportunity_name   VARCHAR(120)    NOT NULL COMMENT '商机名称',
  stage              VARCHAR(30)     DEFAULT 'LEAD' COMMENT '商机阶段',
  source             VARCHAR(30)     DEFAULT NULL COMMENT '商机来源',
  expected_amount    DECIMAL(16,2)   DEFAULT 0.00 COMMENT '预计金额',
  win_rate           DECIMAL(5,2)    DEFAULT 0.00 COMMENT '赢单率',
  expected_sign_date DATE            DEFAULT NULL COMMENT '预计签约日期',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  dept_id            BIGINT(20)      DEFAULT NULL COMMENT '部门ID',
  dept_name          VARCHAR(64)     DEFAULT NULL COMMENT '部门名称',
  contact_id         BIGINT(20)      DEFAULT NULL COMMENT '主联系人ID',
  contact_name       VARCHAR(64)     DEFAULT NULL COMMENT '主联系人姓名',
  latest_follow_up_time DATETIME     DEFAULT NULL COMMENT '最近跟进时间',
  stage_changed_time DATETIME        DEFAULT NULL COMMENT '阶段更新时间',
  lost_reason        VARCHAR(500)    DEFAULT NULL COMMENT '输单原因',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  status             VARCHAR(20)     DEFAULT 'OPEN' COMMENT '状态',
  del_flag           CHAR(1)         DEFAULT '0' COMMENT '删除标志',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (opportunity_id),
  KEY idx_crm_opportunity_customer (customer_id),
  KEY idx_crm_opportunity_stage (stage),
  KEY idx_crm_opportunity_owner (owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM商机表';

DROP TABLE IF EXISTS oa_crm_quote;
CREATE TABLE oa_crm_quote (
  quote_id           BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '报价ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  instance_id        VARCHAR(64)     DEFAULT NULL COMMENT '流程实例ID',
  quote_no           VARCHAR(50)     NOT NULL COMMENT '报价单号',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  customer_name      VARCHAR(120)    DEFAULT NULL COMMENT '客户名称快照',
  opportunity_id     BIGINT(20)      DEFAULT NULL COMMENT '商机ID',
  opportunity_name   VARCHAR(120)    DEFAULT NULL COMMENT '商机名称快照',
  quote_name         VARCHAR(120)    NOT NULL COMMENT '报价名称',
  total_amount       DECIMAL(16,2)   NOT NULL COMMENT '报价总金额',
  tax_amount         DECIMAL(16,2)   DEFAULT 0.00 COMMENT '税额',
  currency           VARCHAR(10)     DEFAULT 'CNY' COMMENT '币种',
  valid_until        DATE            DEFAULT NULL COMMENT '有效期',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  contract_id        BIGINT(20)      DEFAULT NULL COMMENT '关联合同ID',
  contract_no        VARCHAR(50)     DEFAULT NULL COMMENT '关联合同编号',
  attachment_url     VARCHAR(1000)   DEFAULT NULL COMMENT '附件地址',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  status             VARCHAR(20)     DEFAULT 'DRAFT' COMMENT '报价状态',
  del_flag           CHAR(1)         DEFAULT '0' COMMENT '删除标志',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (quote_id),
  UNIQUE KEY uk_crm_quote_no (tenant_id, quote_no),
  KEY idx_crm_quote_customer (customer_id),
  KEY idx_crm_quote_opportunity (opportunity_id),
  KEY idx_crm_quote_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM报价单表';

DROP TABLE IF EXISTS oa_crm_receivable;
CREATE TABLE oa_crm_receivable (
  receivable_id      BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '回款ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  customer_name      VARCHAR(120)    DEFAULT NULL COMMENT '客户名称快照',
  contract_id        BIGINT(20)      DEFAULT NULL COMMENT '合同ID',
  contract_no        VARCHAR(50)     DEFAULT NULL COMMENT '合同编号',
  receivable_no      VARCHAR(50)     NOT NULL COMMENT '回款编号',
  receivable_name    VARCHAR(120)    NOT NULL COMMENT '回款名称',
  planned_amount     DECIMAL(16,2)   NOT NULL COMMENT '计划回款金额',
  received_amount    DECIMAL(16,2)   DEFAULT 0.00 COMMENT '已回款金额',
  outstanding_amount DECIMAL(16,2)   DEFAULT 0.00 COMMENT '未回款金额',
  due_date           DATE            DEFAULT NULL COMMENT '应收日期',
  received_date      DATE            DEFAULT NULL COMMENT '实收日期',
  invoice_status     VARCHAR(20)     DEFAULT 'NONE' COMMENT '发票状态',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  status             VARCHAR(20)     DEFAULT 'PLANNED' COMMENT '回款状态',
  del_flag           CHAR(1)         DEFAULT '0' COMMENT '删除标志',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (receivable_id),
  UNIQUE KEY uk_crm_receivable_no (tenant_id, receivable_no),
  KEY idx_crm_receivable_customer (customer_id),
  KEY idx_crm_receivable_contract (contract_id),
  KEY idx_crm_receivable_due (due_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM回款计划表';

DROP TABLE IF EXISTS oa_crm_renewal;
CREATE TABLE oa_crm_renewal (
  renewal_id         BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '续约ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  instance_id        VARCHAR(64)     DEFAULT NULL COMMENT '流程实例ID',
  renewal_no         VARCHAR(50)     NOT NULL COMMENT '续约编号',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  customer_name      VARCHAR(120)    DEFAULT NULL COMMENT '客户名称快照',
  contract_id        BIGINT(20)      DEFAULT NULL COMMENT '关联合同ID',
  contract_no        VARCHAR(50)     DEFAULT NULL COMMENT '关联合同编号',
  renewal_name       VARCHAR(120)    NOT NULL COMMENT '续约名称',
  renewal_amount     DECIMAL(16,2)   DEFAULT 0.00 COMMENT '续约金额',
  expected_sign_date DATE            DEFAULT NULL COMMENT '预计签约日期',
  current_expire_date DATE           DEFAULT NULL COMMENT '当前到期日期',
  next_expire_date   DATE            DEFAULT NULL COMMENT '续约后到期日期',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  summary            VARCHAR(500)    DEFAULT NULL COMMENT '续约摘要',
  remark             VARCHAR(500)    DEFAULT NULL COMMENT '备注',
  status             VARCHAR(20)     DEFAULT 'PLANNED' COMMENT '续约状态',
  del_flag           CHAR(1)         DEFAULT '0' COMMENT '删除标志',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (renewal_id),
  UNIQUE KEY uk_crm_renewal_no (tenant_id, renewal_no),
  KEY idx_crm_renewal_customer (customer_id),
  KEY idx_crm_renewal_contract (contract_id),
  KEY idx_crm_renewal_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM续约表';

DROP TABLE IF EXISTS oa_crm_service_ticket;
CREATE TABLE oa_crm_service_ticket (
  ticket_id          BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '工单ID',
  tenant_id          BIGINT(20)      DEFAULT 100000 COMMENT '租户ID',
  customer_id        BIGINT(20)      NOT NULL COMMENT '客户ID',
  customer_name      VARCHAR(120)    DEFAULT NULL COMMENT '客户名称快照',
  ticket_no          VARCHAR(50)     NOT NULL COMMENT '工单编号',
  ticket_title       VARCHAR(120)    NOT NULL COMMENT '工单标题',
  severity           VARCHAR(20)     DEFAULT 'LOW' COMMENT '严重度',
  issue_type         VARCHAR(30)     DEFAULT 'OTHER' COMMENT '问题类型',
  owner_id           BIGINT(20)      DEFAULT NULL COMMENT '负责人ID',
  owner_name         VARCHAR(64)     DEFAULT NULL COMMENT '负责人姓名',
  opened_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  resolved_time      DATETIME        DEFAULT NULL COMMENT '解决时间',
  due_time           DATETIME        DEFAULT NULL COMMENT '截止时间',
  description        VARCHAR(1000)   DEFAULT NULL COMMENT '问题描述',
  solution           VARCHAR(1000)   DEFAULT NULL COMMENT '解决方案',
  attachment_url     VARCHAR(1000)   DEFAULT NULL COMMENT '附件地址',
  status             VARCHAR(20)     DEFAULT 'OPEN' COMMENT '工单状态',
  del_flag           CHAR(1)         DEFAULT '0' COMMENT '删除标志',
  create_by          VARCHAR(64)     DEFAULT '' COMMENT '创建者',
  create_time        DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by          VARCHAR(64)     DEFAULT '' COMMENT '更新者',
  update_time        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (ticket_id),
  UNIQUE KEY uk_crm_ticket_no (tenant_id, ticket_no),
  KEY idx_crm_ticket_customer (customer_id),
  KEY idx_crm_ticket_status (status),
  KEY idx_crm_ticket_severity (severity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM服务工单表';

SET FOREIGN_KEY_CHECKS = 1;
