-- 请假申请表
CREATE TABLE IF NOT EXISTS `biz_leave_request` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户ID',
  `instance_id` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `user_id` bigint DEFAULT NULL COMMENT '申请人ID',
  `user_name` varchar(64) DEFAULT NULL COMMENT '申请人姓名',
  `leave_no` varchar(32) DEFAULT NULL COMMENT '请假单号',
  `leave_type` varchar(20) DEFAULT NULL COMMENT '请假类型(ANNUAL年假/SICK病假/PERSONAL事假/MATERNITY产假/MARRIAGE婚假/BEREAVEMENT丧假/OTHER其他)',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `leave_days` decimal(5,1) DEFAULT NULL COMMENT '请假天数',
  `reason` varchar(500) DEFAULT NULL COMMENT '请假事由',
  `attachment_url` varchar(500) DEFAULT NULL COMMENT '附件URL',
  `status` varchar(20) DEFAULT 'DRAFT' COMMENT '状态(DRAFT草稿/PENDING审批中/APPROVED已通过/REJECTED已驳回/CANCELLED已取消)',
  `dept_id` bigint DEFAULT NULL COMMENT '部门ID',
  `dept_name` varchar(64) DEFAULT NULL COMMENT '部门名称',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志(0正常 2删除)',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_leave_no` (`leave_no`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='请假申请表';
