<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.joywon</groupId>
        <artifactId>poco</artifactId>
        <version>5.8.0</version>
    </parent>

    <artifactId>poco-knowledge</artifactId>
    <packaging>jar</packaging>

    <name>poco-knowledge</name>
    <description>知识库模块</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring.ai.version>1.3.0</spring.ai.version>
        <tika.version>2.9.2</tika.version>
        <liteflow.version>2.12.0</liteflow.version>
        <magic.version>3.0.0</magic.version>
        <deepseek4j.version>1.4.6</deepseek4j.version>
        <langchain4j.version>1.0.0-beta2</langchain4j.version>
        <milvus.version>2.5.4</milvus.version>
        <logback-classic.version>1.5.16</logback-classic.version>
        <grpc.version>1.59.1</grpc.version>
        <websearch.version>0.36.0</websearch.version>
        <milvus.version>2.5.4</milvus.version>
        <gitee.api.version>1.1.0</gitee.api.version>
        <github.api.version>1.326</github.api.version>
        <js.engine.version>15.4</js.engine.version>
    </properties>

    <dependencies>
        <!--必备: 操作数据源相关-->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-data</artifactId>
        </dependency>
        <!--必备：poco安全模块-->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-security</artifactId>
        </dependency>
        <!--必备：脱敏工具类-->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-sensitive</artifactId>
        </dependency>
        <!--必备：xss 过滤模块-->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-xss</artifactId>
        </dependency>
        <!--必备: feign 依赖-->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-feign</artifactId>
        </dependency>
        <!--可选：流量治理-->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-sentinel</artifactId>
        </dependency>
        <!--必备: 依赖api模块-->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-app-server-api</artifactId>
        </dependency>
        <!--必备: log 依赖-->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-log</artifactId>
        </dependency>
        <!--选配: mybatis 依赖 -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>
        <!-- druid 连接池 -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-3-starter</artifactId>
        </dependency>
        <!-- mysql -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>
        <!--选配: swagger文档-->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-swagger</artifactId>
        </dependency>
        <!-- 必备：资源解析-->
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-core</artifactId>
            <version>${tika.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-parsers-standard-package</artifactId>
            <version>${tika.version}</version>
        </dependency>
        <!-- 必备：issue api -->
        <dependency>
            <groupId>com.gitee.sdk</groupId>
            <artifactId>gitee5j</artifactId>
            <version>${gitee.api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.kohsuke</groupId>
            <artifactId>github-api</artifactId>
            <version>${github.api.version}</version>
        </dependency>
        <!-- 必备：大模型工具链 -->
        <dependency>
            <groupId>io.github.pig-mesh.ai</groupId>
            <artifactId>spring-ai-core</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-mcp</artifactId>
        </dependency>
        <!-- 必备： langchain4j-reactor 依赖-->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-reactor</artifactId>
        </dependency>
        <!-- 必备： qdrant 存储-->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-qdrant</artifactId>
        </dependency>
        <!--- 选配： milvus 存储-->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-milvus</artifactId>
        </dependency>
        <!--- 选配： chroma 存储-->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-chroma</artifactId>
        </dependency>
        <!-- 必备： apache-pdfbox 解析-->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-document-parser-apache-pdfbox</artifactId>
        </dependency>
        <!-- 必备： apache-poi 解析-->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-document-parser-apache-poi</artifactId>
        </dependency>
        <!-- 选配：本地搜索 -->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-community-web-search-engine-searxng</artifactId>
            <version>${websearch.version}</version>
        </dependency>
        <!-- 必备： 百炼大模型（音频）-->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dashscope-sdk-java</artifactId>
        </dependency>
        <!-- 必备： deepseek -->
        <dependency>
            <groupId>io.github.pig-mesh.ai</groupId>
            <artifactId>deepseek4j-core</artifactId>
            <version>${deepseek4j.version}</version>
        </dependency>
        <!--  必备： 低代码相关-->
        <dependency>
            <groupId>io.github.pig-mesh</groupId>
            <artifactId>magic-api-spring-boot-starter</artifactId>
            <version>${magic.version}</version>
        </dependency>
        <!--  必备： webclient-->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webflux</artifactId>
        </dependency>
        <!--  必备： 安全相关-->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-crypto</artifactId>
        </dependency>
        <!-- 必备： 缓存 -->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-cache</artifactId>
        </dependency>
        <!--必备:  API加解密 -->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-encrypt-api</artifactId>
        </dependency>
        <!--必备：执行脚本-->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-script</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjdk.nashorn</groupId>
            <artifactId>nashorn-core</artifactId>
            <version>${js.engine.version}</version>
            <scope>compile</scope>
        </dependency>
        <!-- 必备：规则引擎-->
        <dependency>
            <groupId>com.yomahub</groupId>
            <artifactId>liteflow-spring-boot-starter</artifactId>
            <version>${liteflow.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-flow-task-api</artifactId>
        </dependency>
        <!-- 节点执行规则渲染 -->
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
        </dependency>
        <!--注册中心客户端-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <!--配置中心客户端-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <!--undertow容器-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback-classic.version}</version>
            </dependency>
            <dependency>
                <groupId>io.milvus</groupId>
                <artifactId>milvus-sdk-java</artifactId>
                <version>${milvus.version}</version>
            </dependency>
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-bom</artifactId>
                <version>${grpc.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.github.pig-mesh.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring.ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-bom</artifactId>
                <version>${langchain4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <profiles>
        <profile>
            <id>cloud</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>repackage</goal>
                                </goals>
                                <configuration>
                                    <loaderImplementation>CLASSIC</loaderImplementation>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>io.fabric8</groupId>
                        <artifactId>docker-maven-plugin</artifactId>
                        <configuration>
                            <skip>false</skip>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>boot</id>
        </profile>
    </profiles>
</project>
