<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~
  ~      Copyright (c) 2018-2025, poco All rights reserved.
  ~
  ~  Redistribution and use in source and binary forms, with or without
  ~  modification, are permitted provided that the following conditions are met:
  ~
  ~ Redistributions of source code must retain the above copyright notice,
  ~  this list of conditions and the following disclaimer.
  ~  Redistributions in binary form must reproduce the above copyright
  ~  notice, this list of conditions and the following disclaimer in the
  ~  documentation and/or other materials provided with the distribution.
  ~  Neither the name of the pig4cloud.com developer nor the names of its
  ~  contributors may be used to endorse or promote products derived from
  ~  this software without specific prior written permission.
  ~  Author: poco
  ~
  -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>cn.joywon</groupId>
		<artifactId>poco</artifactId>
        <version>5.8.0</version>
	</parent>

	<artifactId>poco-common</artifactId>
	<packaging>pom</packaging>

	<description>poco 公共聚合模块</description>

	<modules>
		<module>poco-common-audit</module>
		<module>poco-common-bom</module>
		<module>poco-common-core</module>
		<module>poco-common-data</module>
		<module>poco-common-datasource</module>
		<module>poco-common-excel</module>
		<module>poco-common-encrypt-api</module>
		<module>poco-common-feign</module>
		<module>poco-common-gateway</module>
		<module>poco-common-gray</module>
		<module>poco-common-idempotent</module>
		<module>poco-common-job</module>
		<module>poco-common-log</module>
		<module>poco-common-oss</module>
		<module>poco-common-seata</module>
		<module>poco-common-security</module>
		<module>poco-common-sensitive</module>
		<module>poco-common-sentinel</module>
		<module>poco-common-sequence</module>
		<module>poco-common-swagger</module>
		<module>poco-common-sse</module>
		<module>poco-common-websocket</module>
		<module>poco-common-xss</module>
		<module>poco-common-milvus</module>
	</modules>
</project>
