<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>cloudflow-backend</artifactId>
        <groupId>com.cloudflow</groupId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>cloudflow-common</artifactId>
    <packaging>pom</packaging>
    <description>CloudFlow 公共模块聚合</description>

    <modules>
        <module>cloudflow-common-core</module>
        <module>cloudflow-common-redis</module>
        <module>cloudflow-common-security</module>
        <module>cloudflow-common-data</module>
        <module>cloudflow-common-datasource</module>
        <module>cloudflow-common-log</module>
        <module>cloudflow-common-audit</module>
    </modules>

</project>
