<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.joywon</groupId>
        <artifactId>poco-alliance-merchant</artifactId>
        <version>5.8.0</version>
    </parent>

    <artifactId>poco-alliance-merchant-api</artifactId>

    <dependencies>
        <!-- 连表查询注解 -->
        <dependency>
            <groupId>com.github.yulichang</groupId>
            <artifactId>mybatis-plus-join-annotation</artifactId>
        </dependency>
        <!-- core 工具类 -->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-core</artifactId>
        </dependency>
        <!-- mybatis plus extension, 包含了mybatis plus core -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring</artifactId>
        </dependency>
        <!-- feign 工具类 -->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-feign</artifactId>
        </dependency>
        <!-- excel 导入导出 -->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-excel</artifactId>
        </dependency>
        <!-- 字段审计注解 -->
        <dependency>
            <groupId>org.javers</groupId>
            <artifactId>javers-core</artifactId>
        </dependency>
        <!-- 脱敏工具类 -->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-sensitive</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- 选配: swagger文档 -->
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-swagger</artifactId>
        </dependency>

        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.6.9</version>
        </dependency>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.25.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>cn.joywon</groupId>
            <artifactId>poco-common-security</artifactId>
        </dependency>
    </dependencies>

</project>