import {
  LayoutDashboard, GitMerge, FileText, Settings, LogOut, Bell, CheckCircle2,
  Users, PlayCircle, ShieldCheck, ChevronRight, ChevronDown, FormInput, Code, Megaphone,
  Calendar, Monitor, Rocket, Briefcase, Building2, Wrench, FolderOpen, Car,
  ClipboardCheck, Package, FileArchive, MailOpen, ScrollText, ClipboardList,
  ClipboardEdit, Clock, Plane, BookUser, UserCheck, CalendarClock, LogIn,
  Landmark, SlidersHorizontal, DatabaseZap, BookOpen, FolderTree, Layers3, Send,
  // 补全所有缺失的业务/HR/CRM菜单图标
  Sparkles, Upload, Archive, ListChecks, FileClock, GaugeCircle, Receipt, WalletCards,
  ShoppingCart, Stamp, BadgeCheck, FolderKanban, Banknote, FileSignature, Handshake,
  RotateCcw, ShieldAlert, GitBranch, Target, RefreshCcw, LifeBuoy, Gauge, Boxes,
  BookOpenText, Goal, Anchor, ListOrdered, ArrowRightLeft, IdCard, Wallet, FileCheck2,
  UserCog, CalendarCheck2, CalendarRange, UserPlus, GraduationCap, Award, History,
  Grid3x3, Layers, Sprout, Gift, HeartHandshake, Coins, ShoppingBag, PackageCheck,
  Stethoscope, FileWarning, Search, HeartPulse, BadgeDollarSign, Activity, Scale,
  Gavel, AlertTriangle
} from 'lucide-react';

// 图标名称到组件的映射
export const iconMap: Record<string, React.ElementType> = {
  'LayoutDashboard': LayoutDashboard,
  'GitMerge': GitMerge,
  'FileText': FileText,
  'Settings': Settings,
  'LogOut': LogOut,
  'Bell': Bell,
  'CheckCircle2': CheckCircle2,
  'Users': Users,
  'PlayCircle': PlayCircle,
  'ShieldCheck': ShieldCheck,
  'ChevronRight': ChevronRight,
  'ChevronDown': ChevronDown,
  'FormInput': FormInput,
  'Code': Code,
  'Megaphone': Megaphone,
  'Calendar': Calendar,
  'Monitor': Monitor,
  'Rocket': Rocket,
  'Briefcase': Briefcase,
  'Building2': Building2,
  'Wrench': Wrench,
  'FolderOpen': FolderOpen,
  'Car': Car,
  'ClipboardCheck': ClipboardCheck,
  'Package': Package,
  'FileArchive': FileArchive,
  'MailOpen': MailOpen,
  'ScrollText': ScrollText,
  'ClipboardList': ClipboardList,
  // OA扩展模块图标
  'ClipboardEdit': ClipboardEdit,
  'Clock': Clock,
  'Plane': Plane,
  'BookUser': BookUser,
  'UserCheck': UserCheck,
  'CalendarClock': CalendarClock,
  'LogIn': LogIn,
  // 系统管理扩展图标
  'Landmark': Landmark,
  'SlidersHorizontal': SlidersHorizontal,
  'DatabaseZap': DatabaseZap,
  'BookOpen': BookOpen,
  'FolderTree': FolderTree,
  'Layers3': Layers3,
  'Send': Send,
  // 新增的业务模块映射
  'Sparkles': Sparkles,
  'Upload': Upload,
  'Archive': Archive,
  'ListChecks': ListChecks,
  'FileClock': FileClock,
  'GaugeCircle': GaugeCircle,
  'Receipt': Receipt,
  'WalletCards': WalletCards,
  'ShoppingCart': ShoppingCart,
  'Stamp': Stamp,
  'BadgeCheck': BadgeCheck,
  'FolderKanban': FolderKanban,
  'Banknote': Banknote,
  'FileSignature': FileSignature,
  'Handshake': Handshake,
  'RotateCcw': RotateCcw,
  'ShieldAlert': ShieldAlert,
  'GitBranch': GitBranch,
  'Target': Target,
  'RefreshCcw': RefreshCcw,
  'LifeBuoy': LifeBuoy,
  'Gauge': Gauge,
  'Boxes': Boxes,
  'BookOpenText': BookOpenText,
  'Goal': Goal,
  'Anchor': Anchor,
  'ListOrdered': ListOrdered,
  'ArrowRightLeft': ArrowRightLeft,
  'IdCard': IdCard,
  'Wallet': Wallet,
  'FileCheck2': FileCheck2,
  'UserCog': UserCog,
  'CalendarCheck2': CalendarCheck2,
  'CalendarRange': CalendarRange,
  'UserPlus': UserPlus,
  'GraduationCap': GraduationCap,
  'Award': Award,
  'History': History,
  'Grid3x3': Grid3x3,
  'Layers': Layers,
  'Sprout': Sprout,
  'Gift': Gift,
  'HeartHandshake': HeartHandshake,
  'Coins': Coins,
  'ShoppingBag': ShoppingBag,
  'PackageCheck': PackageCheck,
  'Stethoscope': Stethoscope,
  'FileWarning': FileWarning,
  'Search': Search,
  'HeartPulse': HeartPulse,
  'BadgeDollarSign': BadgeDollarSign,
  'Activity': Activity,
  'Scale': Scale,
  'Gavel': Gavel,
  'AlertTriangle': AlertTriangle,
};

// 获取图标组件，如果找不到则返回默认图标
export const getIcon = (iconName: string): React.ElementType => {
  return iconMap[iconName] || LayoutDashboard;
};
