cloudflow:
  tenant:
    default-tenant-id: 100000

spring:
  cloud:
    gateway:
      lazy-routes-initialization: true
      routes:
        - id: cloudflow-auth
          uri: lb://cloudflow-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: cloudflow-workflow
          uri: lb://cloudflow-service-workflow
          predicates:
            - Path=/workflow/**
          filters:
            - StripPrefix=1

        - id: cloudflow-oa
          uri: lb://cloudflow-oa
          predicates:
            - Path=/oa/**
          filters:
            - StripPrefix=1

        - id: cloudflow-hr
          uri: lb://cloudflow-service-hr
          predicates:
            - Path=/hr/**
          filters:
            - StripPrefix=1

        - id: cloudflow-ws
          uri: lb:ws://cloudflow-service-workflow
          predicates:
            - Path=/ws/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
