<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.joywon</groupId>
        <artifactId>poco-common</artifactId>
        <version>5.8.0</version>
    </parent>

    <artifactId>poco-common-milvus</artifactId>
    <name>LangChain4j Milvus 增强版支持BM25等</name>

    <properties>
        <langchain4j.version>0.36.2</langchain4j.version>
        <milvus.version>2.5.4</milvus.version>
    </properties>


    <dependencies>

        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-core</artifactId>
            <version>${langchain4j.version}</version>
        </dependency>

        <dependency>
            <groupId>io.milvus</groupId>
            <artifactId>milvus-sdk-java</artifactId>
            <version>${milvus.version}</version>
        </dependency>

    </dependencies>


</project>
