spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.cloudflow.auth.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
